(function(){
  "use strict";
  const $=id=>document.getElementById(id),all=(s,r=document)=>Array.from(r.querySelectorAll(s));
  let session=null,data=null,current=null,sponsors=[];
  const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const title=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
  const date=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('en-ZW',{day:'numeric',month:'short',year:'numeric'}):'—';
  const dateTime=v=>v?new Date(v).toLocaleString('en-ZW',{dateStyle:'medium',timeStyle:'short'}):'—';
  const money=v=>'$'+Number(v||0).toFixed(2);
  function toast(text,bad){const n=$('toast');n.textContent=text;n.className='admin-toast'+(bad?' bad':'');n.hidden=false;clearTimeout(n._t);n._t=setTimeout(()=>n.hidden=true,3200);}
  async function rpc(name,args){const {data:result,error}=await amfccDb.rpc(name,args||{});if(error)throw error;return result;}
  function busy(button,on,label){if(!button)return;if(on){button.dataset.label=button.textContent;button.textContent=label||'Working…';button.disabled=true;}else{button.textContent=button.dataset.label||button.textContent;button.disabled=false;}}
  function saveSession(value){session=value;sessionStorage.setItem('amfcc_administration_session',JSON.stringify(value));}
  function restoreSession(){try{session=JSON.parse(sessionStorage.getItem('amfcc_administration_session'));return !!session?.session_token;}catch(_){return false;}}
  function signOut(){session=null;data=null;sessionStorage.removeItem('amfcc_administration_session');$('appShell').hidden=true;$('loginScreen').hidden=false;$('loginPin').value='';}
  function switchView(view){all('.view').forEach(n=>n.classList.toggle('active',n.id==='view-'+view));all('#mainNav button').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='sponsors')loadSponsors();}
  async function load(termId){
    const result=await rpc('registration_admin_bootstrap',{p_session_token:session.session_token,p_term_id:termId?Number(termId):null});
    if(result.status!=='success')throw new Error(result.message||'Administration data could not be loaded.');data=result;render();
  }
  function statusClass(row){if(row.completed_at)return'completed';if(row.student_submitted_at)return'waiting';if(row.student_started_at)return'started';return'not_started';}
  function render(){
    const t=data.selected_term,s=data.summary||{};$('sessionLabel').textContent=session.display_name+(data.can_edit?'':' · Read-only');$('overviewTerm').textContent=t.term_name;
    $('openState').textContent=t.registration_is_open?'Enrolment open':'Enrolment closed';$('openState').className='state-pill '+(t.registration_is_open?'open':'closed');
    $('summaryCards').innerHTML=[[s.expected||0,'Expected'],[s.submitted||0,'Submitted'],[s.not_started||0,'Not started'],[s.draft||0,'Drafts'],[s.completed||0,'Completed']].map(x=>'<button class="summary-card jump" data-view="enrolments"><strong>'+x[0]+'</strong><span>'+x[1]+'</span></button>').join('');
    $('termControl').hidden=!data.can_manage_term;$('termYear').value=t.academic_year;$('termNumber').value=t.term_number;
    $('termSelect').innerHTML=(data.terms||[]).map(term=>'<option value="'+term.id+'" '+(String(term.id)===String(t.id)?'selected':'')+'>'+esc(term.term_name)+(term.registration_is_open?' · OPEN':'')+'</option>').join('');
    const attention=(data.registrations||[]).filter(r=>!r.completed_at).slice(0,8);$('attentionList').innerHTML=attention.length?attention.map(r=>'<button class="attention-row" data-record="'+r.id+'"><span><strong>'+esc(r.student_name)+'</strong><br><small>'+esc(r.registration_number)+'</small></span><span>'+esc(r.status_label)+'</span></button>').join(''):'<div class="notice good">Every expected enrolment is complete.</div>';
    renderRows();renderAccommodation();all('.jump').forEach(b=>b.onclick=()=>switchView(b.dataset.view));all('[data-record]').forEach(b=>b.onclick=()=>openRecord(b.dataset.record));
  }
  function filteredRows(){const q=$('enrolmentSearch').value.trim().toLowerCase(),status=$('statusFilter').value,year=$('classFilter').value,residency=$('residencyFilter').value;return(data.registrations||[]).filter(r=>{
    const statusOk=status==='all'||status==='submitted'&&r.student_submitted_at||status==='not_submitted'&&!r.student_submitted_at||status==='completed'&&r.completed_at||status==='waiting_admin'&&r.student_submitted_at&&!r.completed_at;
    return statusOk&&(year==='all'||String(r.class_year)===year)&&(residency==='all'||r.residency_status===residency)&&(`${r.student_name} ${r.registration_number}`.toLowerCase().includes(q));});}
  function renderRows(){const rows=filteredRows();$('enrolmentRows').innerHTML=rows.length?rows.map(r=>'<tr><td class="student-cell"><strong>'+esc(r.student_name)+'</strong><small>'+esc(r.registration_number)+' · '+(r.class_year?esc(r.class_year)+' year':'Class not set')+'</small></td><td><span class="state-pill '+statusClass(r)+'">'+esc(r.status_label)+'</span></td><td>'+dateTime(r.student_submitted_at)+'</td><td>'+esc(r.sponsor_name||'—')+'<br><small>'+esc(r.sponsor_phone||'')+'</small></td><td>'+esc(r.accommodation_type||'—')+(r.accommodation_residence?'<br><small>'+esc(r.accommodation_residence)+' · '+esc(r.accommodation_room||'')+'</small>':'')+'</td><td class="money">'+money(r.outstanding_balance)+'</td><td><button class="btn secondary compact" data-record="'+r.id+'">View</button></td></tr>').join(''):'<tr><td colspan="7" class="empty">No matching enrolments.</td></tr>';all('#enrolmentRows [data-record]').forEach(b=>b.onclick=()=>openRecord(b.dataset.record));}
  function renderAccommodation(){const q=$('accommodationSearch').value.trim().toLowerCase(),rows=(data.registrations||[]).filter(r=>`${r.student_name} ${r.registration_number} ${r.accommodation_residence||''} ${r.accommodation_room||''}`.toLowerCase().includes(q));$('accommodationRows').innerHTML=rows.length?rows.map(r=>'<tr><td class="student-cell"><strong>'+esc(r.student_name)+'</strong><small>'+esc(r.registration_number)+'</small></td><td>'+esc(r.accommodation_type||'—')+'</td><td>'+esc(r.accommodation_residence||'—')+'</td><td>'+esc(r.accommodation_room||'—')+'</td><td>'+(r.accommodation_complete?'Certified':'Waiting')+'</td><td><button class="btn secondary compact" data-record="'+r.id+'">View</button></td></tr>').join(''):'<tr><td colspan="6" class="empty">No students in this term.</td></tr>';all('#accommodationRows [data-record]').forEach(b=>b.onclick=()=>openRecord(b.dataset.record));}
  const answerLabels={gender:'Gender',marital_status:'Marital status',spouse_location:'Spouse location',identity_number:'ID / passport',sponsor_name:'Sponsor name',sponsor_contact:'Sponsor contact',accommodation_type:'Accommodation type',accommodation_hostel:'Hostel',accommodation_room:'Room',shared_occupants:'Occupants'};
  function value(section,key){return current?.registration?.[section]?.[key]??'';}
  function setValue(id,val){$(id).value=val==null?'':val;}
  async function openRecord(id){
    try{const result=await rpc('registration_admin_get',{p_session_token:session.session_token,p_registration_id:id});if(result.status!=='success')throw new Error(result.message||'Record could not be opened.');current=result;renderRecord();$('recordModal').classList.add('open');$('recordModal').setAttribute('aria-hidden','false');}
    catch(error){toast(error.message,true);}
  }
  function renderRecord(){const r=current.registration,s=current.sponsor||{},i=current.immigration||{};$('recordTitle').textContent=r.student_name_snapshot;$('recordMeta').textContent='Registration '+r.registration_number_snapshot+' · '+current.term.term_name;$('recordStatus').textContent=r.status_label;$('recordStatus').className='state-pill '+statusClass(r);$('recordLock').textContent=r.student_submitted_at?'Student submitted '+dateTime(r.student_submitted_at):'Student has not submitted';
    const answers=r.student_answers||{};$('studentAnswers').innerHTML=Object.keys(answerLabels).map(k=>'<div class="answer"><small>'+answerLabels[k]+'</small>'+esc(answers[k]??'—')+'</div>').join('');
    setValue('sponsorName',s.name||answers.sponsor_name);setValue('sponsorPhone',s.phone||answers.sponsor_contact);setValue('sponsorEmail',s.email);setValue('sponsorRelationship',s.relationship_to_student);setValue('sponsorAddress',s.address);setValue('sponsorNotes',s.notes);
    setValue('arrivalDate',value('admin_answers','official_date_of_arrival'));setValue('feeArrears',value('fees_answers','arrears_previous_terms'));setValue('feePaid',value('fees_answers','amount_paid_current_term'));setValue('feeBalance',value('fees_answers','outstanding_balance'));setValue('paymentPlan',value('fees_answers','payment_plan'));setValue('feesCertifiedBy',value('fees_answers','fees_certified_by'));
    setValue('adminAccommodationType',value('accommodation_answers','accommodation_type')||answers.accommodation_type);setValue('adminHostel',value('accommodation_answers','accommodation_hostel')||answers.accommodation_hostel);setValue('adminRoom',value('accommodation_answers','accommodation_room')||answers.accommodation_room);setValue('adminOccupants',value('accommodation_answers','shared_occupants')||answers.shared_occupants);setValue('accommodationCertifiedBy',value('accommodation_answers','accommodation_certified_by'));setValue('principalSignature',value('final_answers','principal_signature'));setValue('staffNote',r.staff_note);toggleAccommodation();
    $('immigrationSummary').innerHTML=[['Status',title(i.residency_status||'Not recorded')],['Country',i.country],['Nationality',i.nationality],['Passport',i.passport_number],['Passport expiry',date(i.passport_expiry_date)],['Permit',i.permit_type],['Permit number',i.permit_number],['Permit expiry',date(i.permit_expiry_date)]].map(x=>'<div class="answer"><small>'+x[0]+'</small>'+esc(x[1]||'—')+'</div>').join('');
    $('immigrationDocuments').innerHTML=(current.documents||[]).map(d=>'<div class="document-row"><span><strong>'+esc(d.document_type)+'</strong><br><small>'+esc(d.file_name)+'</small></span><button class="btn secondary compact" data-document="'+d.id+'">Download</button></div>').join('')||'<p class="muted">No immigration documents on file.</p>';all('#immigrationDocuments [data-document]').forEach(b=>b.onclick=()=>downloadDocument(b.dataset.document));
    $('historyList').innerHTML=(current.history||[]).map(h=>'<div class="history-row"><span><strong>'+esc(title(h.action))+'</strong><br><small>'+esc(title(h.actor_role))+(h.note?' · '+esc(h.note):'')+'</small></span><small>'+dateTime(h.changed_at)+'</small></div>').join('')||'<p class="muted">No history yet.</p>';
    all('#recordModal input,#recordModal textarea,#recordModal select').forEach(n=>n.disabled=!data.can_edit);$('saveRecord').hidden=!data.can_edit;$('finalizeRecord').hidden=!data.can_edit||!!r.completed_at;
  }
  function toggleAccommodation(){const shared=$('adminAccommodationType').value==='Shared';['adminHostelField','adminRoomField','adminOccupantsField'].forEach(id=>$(id).hidden=!shared);}
  function recordPayload(){return{admin:{official_date_of_arrival:$('arrivalDate').value},fees:{arrears_previous_terms:$('feeArrears').value,amount_paid_current_term:$('feePaid').value,outstanding_balance:$('feeBalance').value,payment_plan:$('paymentPlan').value.trim(),fees_certified_by:$('feesCertifiedBy').value.trim()},accommodation:{accommodation_type:$('adminAccommodationType').value,accommodation_hostel:$('adminHostel').value.trim(),accommodation_room:$('adminRoom').value.trim(),shared_occupants:$('adminOccupants').value?Number($('adminOccupants').value):null,accommodation_certified_by:$('accommodationCertifiedBy').value.trim()},final:{principal_signature:$('principalSignature').value.trim()}};}
  async function saveRecord(finalize){const button=finalize?$('finalizeRecord'):$('saveRecord');if(finalize&&!window.confirm('Complete and lock this official enrolment record?'))return;busy(button,true,finalize?'Completing…':'Saving…');try{
    const sponsor={name:$('sponsorName').value.trim(),phone:$('sponsorPhone').value.trim(),email:$('sponsorEmail').value.trim(),relationship:$('sponsorRelationship').value.trim(),address:$('sponsorAddress').value.trim(),notes:$('sponsorNotes').value.trim()};if(sponsor.name||sponsor.phone){const sr=await rpc('registration_admin_save_sponsor',{p_session_token:session.session_token,p_registration_id:current.registration.id,p_sponsor:sponsor,p_actor_name:session.display_name});if(sr.status!=='success')throw new Error(sr.message);}
    const p=recordPayload(),result=await rpc('registration_admin_save_record',{p_session_token:session.session_token,p_registration_id:current.registration.id,p_admin_answers:p.admin,p_fees_answers:p.fees,p_accommodation_answers:p.accommodation,p_final_answers:p.final,p_staff_note:$('staffNote').value.trim(),p_finalize:finalize,p_actor_name:session.display_name});if(result.status!=='success')throw new Error(result.message||'Record could not be saved.');toast(result.message);await load(data.selected_term.id);await openRecord(current.registration.id);
  }catch(error){toast(error.message||'Record could not be saved.',true);}finally{busy(button,false);}}
  async function makePdf(studentOnly){const r=current.registration,payload=studentOnly?{student_name:r.student_name_snapshot,registration_number:r.registration_number_snapshot,term_name:current.term.term_name,student_answers:r.student_answers,admin_answers:{},fees_answers:{},accommodation_answers:{},final_answers:{}}:{student_name:r.student_name_snapshot,registration_number:r.registration_number_snapshot,term_name:current.term.term_name,student_answers:r.student_answers,admin_answers:r.admin_answers,fees_answers:r.fees_answers,accommodation_answers:r.accommodation_answers,final_answers:r.final_answers};try{AMFCCRegistrationPDF.download(await AMFCCRegistrationPDF.build(payload));}catch(error){toast(error.message,true);}}
  async function loadSponsors(){try{const result=await rpc('registration_admin_sponsors',{p_session_token:session.session_token});if(result.status!=='success')throw new Error(result.message);sponsors=result.sponsors||[];renderSponsors();}catch(error){toast(error.message,true);}}
  function renderSponsors(){const q=$('sponsorSearch').value.trim().toLowerCase(),rows=sponsors.filter(s=>`${s.name} ${s.phone} ${s.email||''}`.toLowerCase().includes(q));$('sponsorRows').innerHTML=rows.length?rows.map(s=>'<tr><td><strong>'+esc(s.name)+'</strong></td><td>'+esc(s.phone)+'</td><td>'+esc(s.email||'—')+'</td><td>'+esc(s.relationship||'—')+'</td><td>'+s.student_count+'</td></tr>').join(''):'<tr><td colspan="5" class="empty">No matching sponsors.</td></tr>';}
  async function downloadDocument(id){try{const response=await fetch(APP_CONFIG.SUPABASE_URL+'/functions/v1/immigration-documents',{method:'POST',headers:{'Content-Type':'application/json','apikey':APP_CONFIG.SUPABASE_PUBLISHABLE_KEY,'Authorization':'Bearer '+APP_CONFIG.SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({session_type:'system',session_token:session.session_token,action:'signed_url',document_id:id})});const result=await response.json();if(!response.ok||result.status!=='success')throw new Error(result.message||'Document could not be opened.');window.open(result.signed_url,'_blank','noopener');}catch(error){toast(error.message,true);}}
  async function manageTerm(action,button){const year=Number($('termYear').value),term=Number($('termNumber').value),actor=$('termActor').value.trim();if(!actor)return toast('Enter your name for the audit record.',true);if(!window.confirm(title(action)+' Term '+term+' '+year+'?'))return;busy(button,true,'Applying…');try{const result=await rpc('registration_admin_manage_term',{p_session_token:session.session_token,p_academic_year:year,p_term_number:term,p_action:action,p_actor_name:actor});if(result.status!=='success')throw new Error(result.message);toast(result.term_name+' updated.');await load(result.term_id);}catch(error){toast(error.message,true);}finally{busy(button,false);}}
  function bind(){
    $('loginForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');busy(b,true,'Opening…');$('loginMessage').hidden=true;try{const result=await rpc('system_control_login',{p_role:$('loginRole').value,p_pin:$('loginPin').value.trim()});if(result.status!=='success')throw new Error(result.message);saveSession(result);$('loginScreen').hidden=true;$('appShell').hidden=false;await load();}catch(error){$('loginMessage').textContent=error.message;$('loginMessage').hidden=false;}finally{busy(b,false);}};
    $('logoutButton').onclick=signOut;$('refreshButton').onclick=()=>load(data?.selected_term?.id).then(()=>toast('Administration refreshed.')).catch(e=>toast(e.message,true));all('#mainNav button,.jump').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('termSelect').onchange=()=>load($('termSelect').value).catch(e=>toast(e.message,true));
    ['enrolmentSearch','statusFilter','classFilter','residencyFilter'].forEach(id=>$(id).addEventListener('input',renderRows));$('accommodationSearch').addEventListener('input',renderAccommodation);$('sponsorSearch').addEventListener('input',renderSponsors);all('#termForm [data-action]').forEach(b=>b.onclick=()=>manageTerm(b.dataset.action,b));
    $('closeRecord').onclick=()=>$('recordModal').classList.remove('open');$('recordModal').onclick=e=>{if(e.target===$('recordModal'))$('recordModal').classList.remove('open');};$('adminAccommodationType').onchange=toggleAccommodation;$('saveRecord').onclick=()=>saveRecord(false);$('finalizeRecord').onclick=()=>saveRecord(true);$('studentPdf').onclick=()=>makePdf(true);$('finalPdf').onclick=()=>makePdf(false);
  }
  document.addEventListener('DOMContentLoaded',async()=>{bind();if(restoreSession()){try{$('loginScreen').hidden=true;$('appShell').hidden=false;await load();}catch(error){signOut();toast(error.message,true);}}});
})();
