const {$,esc,formatDateTime,studentYearLabel,studentYearMatches}=AMFCC;
let pin=sessionStorage.getItem('amfcc_clinic_pin')||'',searchTimer=null,selectedStudent=null,selectedAction='start',activeRows=[],academicYear=AMFCC.currentAcademicYear();

function closeLoginOverlay(){const modal=$('login'),input=$('pin');if(input){input.value='';input.blur();input.disabled=true;}if(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');modal.hidden=true;modal.style.setProperty('display','none','important');modal.style.pointerEvents='none';}document.body.style.overflow='';}
function toast(kind,title,text){$('toastBox').className='result-box '+kind;$('toastBox').innerHTML=`<div class="icon">${kind==='good'?'✓':kind==='warn'?'⚠':'✕'}</div><h2>${esc(title)}</h2><p>${esc(text)}</p>`;$('toast').classList.add('open');setTimeout(()=>$('toast').classList.remove('open'),2400);}
function yearBadge(reg){return `<span class="year-badge">${esc(studentYearLabel(reg,academicYear))}</span>`;}
function yearMatches(reg,filter){return studentYearMatches(reg,filter,academicYear);}
async function login(){pin=$('pin').value.trim();if(!/^\d{4}$/.test(pin)){showPinError('Enter the four-digit clinic password.');return;}const {data,error}=await amfccDb.rpc('clinic_active_bed_rest_v2',{p_pin:pin});if(error||data?.status!=='success'){showPinError(error?.message||data?.message||'Incorrect clinic password.');return;}academicYear=Number(data.current_academic_year)||academicYear;sessionStorage.setItem('amfcc_clinic_pin',pin);closeLoginOverlay();activeRows=data.students||[];renderActive();$('search').focus();}
function showPinError(text){$('pinError').textContent=text;$('pinError').style.display='block';}
async function loadActive(){const {data,error}=await amfccDb.rpc('clinic_active_bed_rest_v2',{p_pin:pin});if(error||data?.status!=='success')return toast('bad','Could not refresh',error?.message||data?.message||'Try again.');academicYear=Number(data.current_academic_year)||academicYear;activeRows=data.students||[];renderActive();}
function renderActive(){const year=$('activeYearFilter').value;const rows=activeRows.filter(s=>yearMatches(s.registration_number,year));$('activeCount').textContent=`${rows.length} student${rows.length===1?'':'s'}`;$('activeBedRest').innerHTML=rows.map(s=>`<div class="student-row bed-rest-card"><div class="bed-rest-icon">🛏️</div><div class="student-main"><span class="student-name-stack"><b>${esc(s.student_name)}</b>${yearBadge(s.registration_number)}</span><div class="student-meta">${esc(s.registration_number)} · Started ${esc(formatDateTime(s.started_at))}${s.residence?` · ${esc(s.residence)} ${esc(s.room||'')}`:''}</div>${s.notes?`<div class="student-meta">${esc(s.notes)}</div>`:''}</div><button class="btn danger" data-clear="${esc(s.registration_number)}" data-name="${esc(s.student_name)}">End bed rest</button></div>`).join('')||'<div class="empty">No students in this class are currently on bed rest.</div>';}
async function searchStudents(){const q=$('search').value.trim(),year=$('clinicYearFilter').value;if(q.length<2&&year==='ALL'){$('searchStatus').textContent='Enter at least two letters or digits, or choose a class year.';$('searchResults').innerHTML='';return;}$('searchStatus').textContent='Searching…';const {data,error}=await amfccDb.rpc('clinic_search_students_v2',{p_pin:pin,p_query:q,p_year_number:year==='ALL'?null:Number(year)});if(error||data?.status!=='success'){$('searchStatus').textContent=error?.message||data?.message||'Search failed.';return;}academicYear=Number(data.current_academic_year)||academicYear;const rows=data.students||[];$('searchStatus').textContent=`${rows.length} match${rows.length===1?'':'es'}`;$('searchResults').innerHTML=rows.map(s=>`<div class="student-row ${s.on_bed_rest?'bed-rest-card':''}"><div class="student-main"><span class="student-name-stack"><b>${s.on_bed_rest?'🛏️ ':''}${esc(s.student_name)}</b>${yearBadge(s.registration_number)}</span><div class="student-meta">${esc(s.registration_number)} · ${s.campus_status==='IN'?'On campus':s.campus_status==='OUT'?'Off campus':'Campus status unknown'}${s.residence?` · ${esc(s.residence)} ${esc(s.room||'')}`:''}</div></div><button class="btn ${s.on_bed_rest?'danger':'good'}" data-action="${s.on_bed_rest?'clear':'start'}" data-reg="${esc(s.registration_number)}" data-name="${esc(s.student_name)}">${s.on_bed_rest?'End bed rest':'Start bed rest'}</button></div>`).join('')||'<div class="empty">No matching students in this class.</div>';}
function openAction(reg,name,action){selectedStudent={registration_number:reg,student_name:name};selectedAction=action;$('bedRestTitle').textContent=action==='start'?'Place student on bed rest':'Remove student from bed rest';$('bedRestStudent').innerHTML=`<b>${esc(name)}</b><br><span class="muted">${esc(reg)} · ${esc(studentYearLabel(reg,academicYear))}</span>`;$('confirmBedRest').textContent=action==='start'?'Confirm bed rest':'End bed rest';$('confirmBedRest').className='btn '+(action==='start'?'good':'danger');$('bedRestNotes').value='';$('bedRestModal').classList.add('open');}
async function confirmAction(){if(!selectedStudent)return;const {data,error}=await amfccDb.rpc('clinic_set_bed_rest',{p_pin:pin,p_registration_number:selectedStudent.registration_number,p_action:selectedAction,p_notes:$('bedRestNotes').value.trim()||null});if(error||data?.status!=='success')return toast('bad','Not saved',error?.message||data?.message||'Try again.');$('bedRestModal').classList.remove('open');toast('good','Saved',data.message);await loadActive();await searchStudents();}
$('loginBtn').onclick=login;$('pin').onkeydown=e=>{if(e.key==='Enter')login();};$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(searchStudents,250);};$('clinicYearFilter').onchange=searchStudents;$('activeYearFilter').onchange=renderActive;$('searchResults').onclick=e=>{const b=e.target.closest('[data-action]');if(b)openAction(b.dataset.reg,b.dataset.name,b.dataset.action);};$('activeBedRest').onclick=e=>{const b=e.target.closest('[data-clear]');if(b)openAction(b.dataset.clear,b.dataset.name,'clear');};$('refresh').onclick=loadActive;$('confirmBedRest').onclick=confirmAction;$('cancelBedRest').onclick=()=>$('bedRestModal').classList.remove('open');$('toast').onclick=()=>$('toast').classList.remove('open');if(pin){$('pin').value=pin;login();}else $('pin').focus();
