const {$,esc,formatDateTime,localDate,downloadCsv}=AMFCC;
let pin=sessionStorage.getItem('amfcc_dashboard_pin')||'',dataCache=null,timer=null,reviewPassId=null;
function toast(kind,title,text){$('toastBox').className='result-box '+kind;$('toastBox').innerHTML=`<div class="icon">${kind==='good'?'✓':kind==='warn'?'⚠':'✕'}</div><h2>${esc(title)}</h2><p>${esc(text)}</p>`;$('toast').classList.add('open');setTimeout(()=>$('toast').classList.remove('open'),2600)}
async function load(){if(!pin)return false;const {data,error}=await amfccDb.rpc('student_services_dashboard',{p_pin:pin});if(error||data?.status!=='success'){$('pinError').textContent=error?.message||data?.message||'Incorrect PIN.';$('pinError').style.display='block';return false}dataCache=data;render();$('updated').textContent='Updated '+new Date().toLocaleTimeString('en-ZW');return true}
function render(){const c=dataCache.counts||{};$('onCount').textContent=c.on_campus||0;$('offCount').textContent=c.off_campus||0;$('pendingCount').textContent=c.pending_passes||0;$('overdueCount').textContent=c.overdue_passes||0;renderCampus();renderPasses();renderDuty();renderRecent()}
function renderCampus(){const q=$('campusSearch').value.toLowerCase(),filter=$('campusFilter').value;const rows=(dataCache.students||[]).filter(s=>(filter==='ALL'||s.status===filter)&&(`${s.student_name} ${s.registration_number}`.toLowerCase().includes(q)));$('campusRows').innerHTML=rows.map(s=>`<tr><td><b>${esc(s.student_name)}</b></td><td>${esc(s.registration_number)}</td><td><span class="pill ${esc(s.status)}">${s.status==='IN'?'ON CAMPUS':s.status==='OUT'?'OFF CAMPUS':'UNKNOWN'}</span></td><td>${esc(formatDateTime(s.last_movement_at))}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">No matching students.</td></tr>'}
function approvalSummary(pass){const approvals=pass.approvals||[];const admin=approvals.find(a=>a.role==='administrator');const senior=approvals.find(a=>['principal','dean','director'].includes(a.role)&&a.decision==='approved');return `Admin: ${admin?admin.decision:'waiting'}<br>Senior: ${senior?senior.role:'waiting'}`}
function renderPasses(){const q=$('passSearch').value.toLowerCase(),filter=$('passFilter').value;const rows=(dataCache.gate_passes||[]).filter(p=>(filter==='ALL'||p.status===filter)&&(`${p.student_name} ${p.registration_number} ${p.destination}`.toLowerCase().includes(q)));$('passRows').innerHTML=rows.map(p=>`<tr class="${p.overdue?'overdue':''}"><td><b>${esc(p.student_name)}</b><br><small>${esc(p.registration_number)}</small></td><td>${esc(p.destination)}</td><td>${esc(formatDateTime(p.departure_at))}<br><small>Return ${esc(formatDateTime(p.expected_return_at))}</small></td><td><span class="pill ${p.overdue?'overdue':esc(p.status)}">${p.overdue?'OVERDUE':esc(p.status.toUpperCase())}</span></td><td>${approvalSummary(p)}</td><td><button class="btn secondary" data-review="${esc(p.id)}">Review</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No matching gate passes.</td></tr>'}
function renderDuty(){$('dutyRows').innerHTML=(dataCache.gate_duty_today||[]).map(r=>`<tr><td>${esc(formatDateTime(r.scanned_at))}</td><td><b>${esc(r.student_name)}</b></td><td>${esc(r.registration_number)}</td><td><span class="pill ${esc(r.direction)}">${esc(r.direction)}</span></td><td>${esc(r.source)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No gate duty records today.</td></tr>'}
function renderRecent(){$('recentRows').innerHTML=(dataCache.recent_movements||[]).map(r=>`<tr><td>${esc(formatDateTime(r.scanned_at))}</td><td><b>${esc(r.student_name)}</b></td><td>${esc(r.registration_number)}</td><td><span class="pill ${esc(r.direction)}">${esc(r.direction)}</span></td><td>${r.gate_pass_id?'Linked':'Not linked'}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No campus movements recorded.</td></tr>'}
function openReview(id){const p=(dataCache.gate_passes||[]).find(x=>x.id===id);if(!p)return;reviewPassId=id;const approvals=(p.approvals||[]).map(a=>`<div class="approval-row"><b>${esc(a.role)}</b><span>${esc(a.decision)} · ${esc(formatDateTime(a.decided_at))}</span></div>`).join('')||'<p class="muted">No decisions yet.</p>';$('reviewDetails').innerHTML=`<p><b>${esc(p.student_name)}</b> (${esc(p.registration_number)})</p><p><b>Destination:</b> ${esc(p.destination)}</p><p><b>Reason:</b> ${esc(p.reason)}</p><p><b>Departure:</b> ${esc(formatDateTime(p.departure_at))}</p><p><b>Expected return:</b> ${esc(formatDateTime(p.expected_return_at))}</p><p><b>Contact:</b> ${esc(p.contact_details)}</p><p><b>Status:</b> ${esc(p.status)}</p><h3>Signatures and decisions</h3><div class="approval-list">${approvals}</div>`;$('reviewModal').classList.add('open')}
async function decide(decision){const role=$('actorRole').value;if(!role)return toast('warn','Choose a role','Select who is approving or rejecting.');const comments=$('decisionComments').value.trim();if(['rejected','cancelled'].includes(decision)&&!comments)return toast('warn','Add a reason','A rejection or cancellation reason is required.');const {data,error}=await amfccDb.rpc('dashboard_gate_pass_decision',{p_pin:pin,p_pass_id:reviewPassId,p_actor_role:role,p_decision:decision,p_comments:comments||null});if(error||data?.status!=='success')return toast('bad','Not saved',error?.message||data?.message||'Try again.');$('reviewModal').classList.remove('open');$('decisionComments').value='';toast('good','Decision saved',`The pass is now ${data.pass_status}.`);load()}
async function login(){pin=$('pin').value.trim();if(!/^\d{4}$/.test(pin)){$('pinError').textContent='Enter the four-digit PIN.';$('pinError').style.display='block';return}const ok=await load();if(ok){sessionStorage.setItem('amfcc_dashboard_pin',pin);$('login').classList.remove('open');clearInterval(timer);timer=setInterval(load,10000)}}
async function exportReport(){const type=$('reportType').value,start=$('startDate').value||null,end=$('endDate').value||null;const {data,error}=await amfccDb.rpc('student_services_export',{p_pin:pin,p_report:type,p_start_date:start,p_end_date:end});if(error||data?.status!=='success')return toast('bad','Export failed',error?.message||data?.message||'Try again.');try{downloadCsv(data.rows||[],`${type}-${start||'start'}-${end||localDate()}.csv`)}catch(e){toast('warn','No records',e.message)}}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.section').forEach(s=>s.classList.toggle('active',s.id===b.dataset.tab))});document.addEventListener('click',e=>{const b=e.target.closest('[data-review]');if(b)openReview(b.dataset.review)});document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>decide(b.dataset.decision));$('closeReview').onclick=()=>$('reviewModal').classList.remove('open');$('loginBtn').onclick=login;$('pin').onkeydown=e=>{if(e.key==='Enter')login()};$('campusSearch').oninput=renderCampus;$('campusFilter').onchange=renderCampus;$('passSearch').oninput=renderPasses;$('passFilter').onchange=renderPasses;$('refresh').onclick=load;$('exportReport').onclick=exportReport;$('toast').onclick=()=>$('toast').classList.remove('open');const today=localDate(),past=new Date(Date.now()-30*86400000).toISOString().slice(0,10);$('startDate').value=past;$('endDate').value=today;if(pin){$('pin').value=pin;login()}else $('pin').focus();
