-- AMFCC Student Services Platform v6
-- Separate School Administration site, term fee status and School Holiday Mode.

-- 1. School Holiday Mode setting.
INSERT INTO public.system_settings(setting_key,setting_value,description)
VALUES(
  'school_holiday_mode',
  'false'::jsonb,
  'When true, gate passes may be submitted at any time and require only the School Administrator approval.'
)
ON CONFLICT(setting_key) DO NOTHING;

-- 2. Academic terms and simple paid/not-paid fee tracking.
CREATE TABLE IF NOT EXISTS public.academic_terms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  academic_year integer NOT NULL CHECK (academic_year BETWEEN 2020 AND 2100),
  term_number integer NOT NULL CHECK (term_number BETWEEN 1 AND 3),
  term_name text NOT NULL,
  fees_due_date date NOT NULL,
  is_current boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(academic_year,term_number)
);

CREATE UNIQUE INDEX IF NOT EXISTS academic_terms_one_current_idx
ON public.academic_terms(is_current)
WHERE is_current=true;

CREATE TABLE IF NOT EXISTS public.student_term_fee_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id text NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  term_id bigint NOT NULL REFERENCES public.academic_terms(id) ON DELETE RESTRICT,
  fees_paid boolean NOT NULL DEFAULT true,
  notes text,
  updated_by_role text NOT NULL DEFAULT 'administrator',
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(student_id,term_id)
);

CREATE INDEX IF NOT EXISTS student_term_fee_status_term_idx
ON public.student_term_fee_status(term_id,fees_paid);

ALTER TABLE public.academic_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_term_fee_status ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.academic_terms,public.student_term_fee_status FROM anon,authenticated;

INSERT INTO public.academic_terms(academic_year,term_number,term_name,fees_due_date,is_current)
VALUES
  (2026,1,'Term 1 2026',DATE '2026-01-15',false),
  (2026,2,'Term 2 2026',DATE '2026-05-05',true),
  (2026,3,'Term 3 2026',DATE '2026-09-05',false)
ON CONFLICT(academic_year,term_number) DO UPDATE
SET term_name=excluded.term_name,
    fees_due_date=excluded.fees_due_date,
    updated_at=now();

UPDATE public.academic_terms
SET is_current=(academic_year=2026 AND term_number=2),updated_at=now()
WHERE academic_year=2026;

-- The user requested that every student initially shows as fees paid.
INSERT INTO public.student_term_fee_status(student_id,term_id,fees_paid,notes,updated_by_role)
SELECT s.id,t.id,true,'Initial v6 setup: marked paid pending Administration review.','administrator'
FROM public.students s
CROSS JOIN public.academic_terms t
WHERE s.is_active=true AND t.academic_year=2026
ON CONFLICT(student_id,term_id) DO NOTHING;

-- 3. Student gate-pass submission observes School Holiday Mode.
CREATE OR REPLACE FUNCTION public.student_submit_gate_pass(
  p_registration_number text,
  p_destination text,
  p_reason text,
  p_departure_at timestamptz,
  p_expected_return_at timestamptz,
  p_contact_details text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_student public.students%rowtype;
  v_pass public.gate_passes%rowtype;
  v_deadline timestamptz;
  v_pilot boolean;
  v_pilot_end jsonb;
  v_holiday boolean := false;
BEGIN
  SELECT * INTO v_student
  FROM public.students
  WHERE registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    AND is_active=true
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('status','not_found','message','Student registration number was not found.');
  END IF;

  IF length(trim(coalesce(p_destination,'')))<2
     OR length(trim(coalesce(p_reason,'')))<3
     OR length(trim(coalesce(p_contact_details,'')))<3 THEN
    RETURN jsonb_build_object('status','invalid','message','Complete the destination, reason and contact details.');
  END IF;

  IF p_departure_at IS NULL OR p_expected_return_at IS NULL OR p_expected_return_at<=p_departure_at THEN
    RETURN jsonb_build_object('status','invalid','message','Expected return must be later than departure.');
  END IF;

  IF p_departure_at<=now() THEN
    RETURN jsonb_build_object('status','invalid','message','Departure must be in the future.');
  END IF;

  SELECT coalesce((setting_value #>> '{}')::boolean,false)
  INTO v_holiday
  FROM public.system_settings
  WHERE setting_key='school_holiday_mode';

  IF NOT coalesce(v_holiday,false) THEN
    v_deadline:=public._gate_pass_deadline(p_departure_at);
    IF now()>v_deadline THEN
      RETURN jsonb_build_object(
        'status','deadline_closed',
        'message','The Wednesday 4:00 pm submission deadline has passed. Contact School Administration for an emergency request.',
        'deadline',v_deadline,
        'school_holiday_mode',false
      );
    END IF;
  ELSE
    v_deadline:=NULL;
  END IF;

  IF EXISTS(
    SELECT 1 FROM public.gate_passes
    WHERE student_id=v_student.id
      AND status IN ('pending','approved','departed')
      AND tstzrange(departure_at,expected_return_at,'[]') && tstzrange(p_departure_at,p_expected_return_at,'[]')
  ) THEN
    RETURN jsonb_build_object('status','duplicate_request','message','An active gate pass already overlaps this period.');
  END IF;

  INSERT INTO public.gate_passes(student_id,destination,reason,departure_at,expected_return_at,contact_details)
  VALUES(v_student.id,trim(p_destination),trim(p_reason),p_departure_at,p_expected_return_at,trim(p_contact_details))
  RETURNING * INTO v_pass;

  INSERT INTO public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
  VALUES(v_pass.id,NULL,'pending','student',
    CASE WHEN v_holiday THEN 'Gate pass submitted during School Holiday Mode.' ELSE 'Gate pass submitted.' END);

  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('gate_pass','gate_pass',v_pass.id::text,'student','submitted',
    jsonb_build_object('student_id',v_student.id,'registration_number',v_student.registration_number,'school_holiday_mode',v_holiday));

  SELECT coalesce((setting_value #>> '{}')::boolean,false) INTO v_pilot
  FROM public.system_settings WHERE setting_key='gate_pass_pilot_mode';
  SELECT setting_value INTO v_pilot_end
  FROM public.system_settings WHERE setting_key='gate_pass_pilot_ends_at';

  RETURN jsonb_build_object(
    'status','success','pass_id',v_pass.id,'student_name',v_student.full_name,
    'registration_number',v_student.registration_number,'pass_status',v_pass.status,
    'deadline',v_deadline,'pilot_mode',v_pilot,'pilot_ends_at',v_pilot_end,
    'school_holiday_mode',v_holiday,
    'approval_rule',CASE WHEN v_holiday THEN 'School Administrator approval only' ELSE 'School Administrator plus Principal, Dean or Director' END
  );
END;
$$;

-- 4. Student pass status shows the correct approval rule.
CREATE OR REPLACE FUNCTION public.student_gate_pass_status(p_registration_number text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_student public.students%rowtype;
  v_passes jsonb;
  v_pilot boolean;
  v_pilot_end jsonb;
  v_holiday boolean := false;
BEGIN
  SELECT * INTO v_student
  FROM public.students
  WHERE registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    AND is_active=true
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('status','not_found','message','Student registration number was not found.');
  END IF;

  SELECT coalesce((setting_value #>> '{}')::boolean,false) INTO v_holiday
  FROM public.system_settings WHERE setting_key='school_holiday_mode';

  SELECT coalesce(jsonb_agg(item ORDER BY submitted_at DESC),'[]'::jsonb)
  INTO v_passes
  FROM (
    SELECT p.submitted_at,jsonb_build_object(
      'id',p.id,'destination',p.destination,'reason',p.reason,
      'departure_at',p.departure_at,'expected_return_at',p.expected_return_at,
      'status',p.status,'submitted_at',p.submitted_at,'final_approved_at',p.final_approved_at,
      'actual_departure_at',p.actual_departure_at,'actual_return_at',p.actual_return_at,
      'paper_pass_checked',p.paper_pass_checked,'cancellation_reason',p.cancellation_reason,
      'approvals',coalesce((
        SELECT jsonb_agg(jsonb_build_object(
          'role',a.approver_role,'decision',a.decision,'comments',a.comments,'decided_at',a.decided_at
        ) ORDER BY a.decided_at)
        FROM public.gate_pass_approvals a WHERE a.pass_id=p.id
      ),'[]'::jsonb),
      'waiting_on',CASE
        WHEN p.status<>'pending' THEN NULL
        WHEN NOT EXISTS(
          SELECT 1 FROM public.gate_pass_approvals a
          WHERE a.pass_id=p.id AND a.approver_role='administrator' AND a.decision='approved'
        ) THEN 'School Administrator'
        WHEN NOT v_holiday AND NOT EXISTS(
          SELECT 1 FROM public.gate_pass_approvals a
          WHERE a.pass_id=p.id AND a.approver_role IN ('principal','dean','director') AND a.decision='approved'
        ) THEN 'Principal, Dean or Director'
        ELSE NULL
      END
    ) item
    FROM public.gate_passes p
    WHERE p.student_id=v_student.id
    ORDER BY p.submitted_at DESC
    LIMIT 20
  ) q;

  SELECT coalesce((setting_value #>> '{}')::boolean,false) INTO v_pilot
  FROM public.system_settings WHERE setting_key='gate_pass_pilot_mode';
  SELECT setting_value INTO v_pilot_end
  FROM public.system_settings WHERE setting_key='gate_pass_pilot_ends_at';

  RETURN jsonb_build_object(
    'status','success','student_name',v_student.full_name,
    'registration_number',v_student.registration_number,'passes',v_passes,
    'pilot_mode',v_pilot,'pilot_ends_at',v_pilot_end,
    'school_holiday_mode',v_holiday,
    'approval_rule',CASE WHEN v_holiday THEN 'School Administrator approval only' ELSE 'School Administrator plus Principal, Dean or Director' END,
    'submission_deadline_active',(NOT v_holiday)
  );
END;
$$;

-- 5. Shared Management and Student Leadership dashboard. School Administrator decisions are removed from this site.
CREATE OR REPLACE FUNCTION public.student_services_dashboard(p_pin text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_access text;
  v_students jsonb;
  v_recent jsonb;
  v_passes jsonb;
  v_duty jsonb;
  v_settings jsonb;
  v_on integer; v_off integer; v_unknown integer;
  v_pending integer; v_approved integer; v_overdue integer;
  v_bed_rest integer; v_maternity integer;
  v_holiday boolean := false;
BEGIN
  v_access:=CASE WHEN p_pin='0593' THEN 'management' WHEN p_pin='1960' THEN 'student_leadership' ELSE NULL END;
  IF v_access IS NULL THEN RETURN jsonb_build_object('status','unauthorized','message','Incorrect password.'); END IF;

  SELECT coalesce((setting_value #>> '{}')::boolean,false) INTO v_holiday
  FROM public.system_settings WHERE setting_key='school_holiday_mode';

  WITH latest AS (
    SELECT DISTINCT ON (cm.student_id) cm.student_id,cm.direction,cm.scanned_at,gd.device_name,gd.location
    FROM public.campus_movements cm JOIN public.gate_devices gd ON gd.id=cm.gate_device_id
    ORDER BY cm.student_id,cm.scanned_at DESC,cm.id DESC
  ), roster AS (
    SELECT s.id,s.registration_number,s.full_name,coalesce(l.direction,'UNKNOWN') status,
           l.scanned_at,l.device_name,l.location,
           (br.id IS NOT NULL) bed_rest,br.started_at bed_rest_started_at,br.notes bed_rest_notes,
           (mat.id IS NOT NULL) maternity,
           aa.residence,aa.room,aa.bed,aa.allocation_status
    FROM public.students s
    LEFT JOIN latest l ON l.student_id=s.id
    LEFT JOIN LATERAL (
      SELECT x.id,x.started_at,x.notes FROM public.student_support_statuses x
      WHERE x.student_id=s.id AND x.status_type='bed_rest' AND x.is_active=true
      ORDER BY x.started_at DESC LIMIT 1
    ) br ON true
    LEFT JOIN LATERAL (
      SELECT x.id FROM public.student_support_statuses x
      WHERE x.student_id=s.id AND x.status_type='maternity' AND x.is_active=true
      ORDER BY x.started_at DESC LIMIT 1
    ) mat ON true
    LEFT JOIN LATERAL (
      SELECT a.residence,a.room,a.bed,a.allocation_status FROM public.accommodation_allocations a
      WHERE a.student_id=s.id AND a.is_active=true ORDER BY a.allocated_at DESC LIMIT 1
    ) aa ON true
    WHERE s.is_active=true
  )
  SELECT count(*) FILTER(WHERE status='IN'),count(*) FILTER(WHERE status='OUT'),count(*) FILTER(WHERE status='UNKNOWN'),
         count(*) FILTER(WHERE bed_rest),count(*) FILTER(WHERE maternity),
         coalesce(jsonb_agg(jsonb_build_object(
           'student_id',id,'registration_number',registration_number,'student_name',full_name,
           'status',status,'last_movement_at',scanned_at,'device_name',device_name,'location',location,
           'bed_rest',bed_rest,'bed_rest_started_at',bed_rest_started_at,'bed_rest_notes',bed_rest_notes,
           'maternity',maternity,'residence',residence,'room',room,'bed',bed,'accommodation_status',allocation_status
         ) ORDER BY full_name),'[]'::jsonb)
  INTO v_on,v_off,v_unknown,v_bed_rest,v_maternity,v_students FROM roster;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'id',x.id,'registration_number',x.registration_number,'student_name',x.full_name,
    'direction',x.direction,'scanned_at',x.scanned_at,'device_name',x.device_name,'location',x.location,
    'gate_pass_id',x.gate_pass_id,'checkout_destination_code',x.checkout_destination_code,
    'checkout_destination_label',x.checkout_destination_label
  ) ORDER BY x.scanned_at DESC),'[]'::jsonb)
  INTO v_recent
  FROM (
    SELECT cm.id,s.registration_number,s.full_name,cm.direction,cm.scanned_at,gd.device_name,gd.location,
           cm.gate_pass_id,cm.checkout_destination_code,cm.checkout_destination_label
    FROM public.campus_movements cm JOIN public.students s ON s.id=cm.student_id
    JOIN public.gate_devices gd ON gd.id=cm.gate_device_id
    ORDER BY cm.scanned_at DESC,cm.id DESC LIMIT 150
  ) x;

  SELECT count(*) FILTER(WHERE status='pending'),count(*) FILTER(WHERE status='approved'),
         count(*) FILTER(WHERE status='departed' AND expected_return_at<now())
  INTO v_pending,v_approved,v_overdue FROM public.gate_passes;

  SELECT coalesce(jsonb_agg(item ORDER BY submitted_at DESC),'[]'::jsonb) INTO v_passes
  FROM (
    SELECT p.submitted_at,jsonb_build_object(
      'id',p.id,'student_id',p.student_id,'student_name',s.full_name,'registration_number',s.registration_number,
      'destination',p.destination,'reason',p.reason,'contact_details',p.contact_details,
      'departure_at',p.departure_at,'expected_return_at',p.expected_return_at,'submitted_at',p.submitted_at,
      'status',p.status,'final_approved_at',p.final_approved_at,'actual_departure_at',p.actual_departure_at,
      'actual_return_at',p.actual_return_at,'paper_pass_checked',p.paper_pass_checked,
      'cancellation_reason',p.cancellation_reason,'overdue',(p.status='departed' AND p.expected_return_at<now()),
      'approvals',coalesce((SELECT jsonb_agg(jsonb_build_object(
        'role',a.approver_role,'decision',a.decision,'comments',a.comments,'decided_at',a.decided_at
      ) ORDER BY a.decided_at) FROM public.gate_pass_approvals a WHERE a.pass_id=p.id),'[]'::jsonb),
      'waiting_on',CASE
        WHEN p.status<>'pending' THEN NULL
        WHEN NOT EXISTS(SELECT 1 FROM public.gate_pass_approvals a WHERE a.pass_id=p.id AND a.approver_role='administrator' AND a.decision='approved') THEN 'School Administrator'
        WHEN NOT v_holiday AND NOT EXISTS(SELECT 1 FROM public.gate_pass_approvals a WHERE a.pass_id=p.id AND a.approver_role IN ('principal','dean','director') AND a.decision='approved') THEN 'Principal, Dean or Director'
        ELSE NULL END
    ) item
    FROM public.gate_passes p JOIN public.students s ON s.id=p.student_id
    ORDER BY p.submitted_at DESC LIMIT 300
  ) q;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'id',x.id,'student_name',x.full_name,'registration_number',x.registration_number,
    'direction',x.direction,'scanned_at',x.scanned_at,'source',x.record_source
  ) ORDER BY x.scanned_at DESC),'[]'::jsonb)
  INTO v_duty
  FROM (
    SELECT g.id,s.full_name,s.registration_number,g.direction,g.scanned_at,g.record_source
    FROM public.gate_duty_records g JOIN public.students s ON s.id=g.student_id
    WHERE (g.scanned_at AT TIME ZONE 'Africa/Harare')::date=(now() AT TIME ZONE 'Africa/Harare')::date
    ORDER BY g.scanned_at DESC LIMIT 200
  ) x;

  IF v_access='management' THEN
    SELECT coalesce(jsonb_object_agg(setting_key,setting_value),'{}'::jsonb) INTO v_settings FROM public.system_settings;
  ELSE v_settings:='{}'::jsonb; END IF;

  RETURN jsonb_build_object(
    'status','success','access_level',v_access,
    'can_review_passes',(v_access='management'),'can_manage_settings',(v_access='management'),
    'school_holiday_mode',v_holiday,
    'counts',jsonb_build_object('on_campus',v_on,'off_campus',v_off,'unknown',v_unknown,
      'pending_passes',v_pending,'approved_passes',v_approved,'overdue_passes',v_overdue,
      'bed_rest',v_bed_rest,'maternity',v_maternity),
    'students',v_students,'recent_movements',v_recent,'gate_passes',v_passes,
    'gate_duty_today',v_duty,'settings',v_settings
  );
END;
$$;

-- 6. Management decisions are now Principal, Dean or Director only.
CREATE OR REPLACE FUNCTION public.dashboard_gate_pass_decision(
  p_pin text,
  p_pass_id uuid,
  p_actor_role text,
  p_decision text,
  p_comments text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_pass public.gate_passes%rowtype;
  v_old text;
  v_new text;
  v_admin boolean;
  v_senior boolean;
  v_holiday boolean := false;
BEGIN
  IF p_pin<>'0593' THEN RETURN jsonb_build_object('status','unauthorized','message','Management password required.'); END IF;
  IF p_actor_role NOT IN ('principal','dean','director') THEN
    RETURN jsonb_build_object('status','invalid','message','Choose Principal, Dean or Director. School Administrator approval is completed on the separate Admin site.');
  END IF;
  IF p_decision NOT IN ('approved','rejected','cancelled') THEN
    RETURN jsonb_build_object('status','invalid','message','Choose Approve, Reject or Cancel.');
  END IF;

  SELECT * INTO v_pass FROM public.gate_passes WHERE id=p_pass_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found','message','Gate pass not found.'); END IF;
  v_old:=v_pass.status;

  INSERT INTO public.gate_pass_approvals(pass_id,approver_role,decision,comments,decided_at)
  VALUES(p_pass_id,p_actor_role,p_decision,nullif(trim(coalesce(p_comments,'')),''),now())
  ON CONFLICT(pass_id,approver_role) DO UPDATE
  SET decision=excluded.decision,comments=excluded.comments,decided_at=excluded.decided_at;

  SELECT coalesce((setting_value #>> '{}')::boolean,false) INTO v_holiday
  FROM public.system_settings WHERE setting_key='school_holiday_mode';

  IF p_decision='cancelled' THEN
    v_new:='cancelled';
    UPDATE public.gate_passes
    SET status=v_new,cancelled_at=now(),cancelled_by_role=p_actor_role,
        cancellation_reason=nullif(trim(coalesce(p_comments,'')),''),updated_at=now()
    WHERE id=p_pass_id;
  ELSIF p_decision='rejected' THEN
    v_new:='rejected';
    UPDATE public.gate_passes SET status=v_new,updated_at=now() WHERE id=p_pass_id;
  ELSE
    SELECT exists(SELECT 1 FROM public.gate_pass_approvals
      WHERE pass_id=p_pass_id AND approver_role='administrator' AND decision='approved') INTO v_admin;
    SELECT exists(SELECT 1 FROM public.gate_pass_approvals
      WHERE pass_id=p_pass_id AND approver_role IN ('principal','dean','director') AND decision='approved') INTO v_senior;

    IF v_admin AND (v_holiday OR v_senior) THEN
      v_new:='approved';
      UPDATE public.gate_passes
      SET status='approved',final_approved_at=coalesce(final_approved_at,now()),updated_at=now()
      WHERE id=p_pass_id;
    ELSE
      v_new:='pending';
      UPDATE public.gate_passes SET status='pending',updated_at=now() WHERE id=p_pass_id;
    END IF;
  END IF;

  INSERT INTO public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
  VALUES(p_pass_id,v_old,v_new,p_actor_role,nullif(trim(coalesce(p_comments,'')),''));
  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('gate_pass','gate_pass',p_pass_id::text,p_actor_role,p_decision,
    jsonb_build_object('previous_status',v_old,'new_status',v_new,'comments',p_comments,'school_holiday_mode',v_holiday));

  RETURN jsonb_build_object('status','success','pass_id',p_pass_id,'pass_status',v_new,
    'actor_role',p_actor_role,'decision',p_decision,'school_holiday_mode',v_holiday);
END;
$$;

-- 7. School Administrator decisions are isolated behind password 1972.
CREATE OR REPLACE FUNCTION public.admin_gate_pass_decision(
  p_pin text,
  p_pass_id uuid,
  p_decision text,
  p_comments text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_pass public.gate_passes%rowtype;
  v_old text;
  v_new text;
  v_admin boolean;
  v_senior boolean;
  v_holiday boolean := false;
BEGIN
  IF p_pin<>'1972' THEN RETURN jsonb_build_object('status','unauthorized','message','School Administration password required.'); END IF;
  IF p_decision NOT IN ('approved','rejected','cancelled') THEN
    RETURN jsonb_build_object('status','invalid','message','Choose Approve, Reject or Cancel.');
  END IF;

  SELECT * INTO v_pass FROM public.gate_passes WHERE id=p_pass_id FOR UPDATE;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found','message','Gate pass not found.'); END IF;
  v_old:=v_pass.status;

  INSERT INTO public.gate_pass_approvals(pass_id,approver_role,decision,comments,decided_at)
  VALUES(p_pass_id,'administrator',p_decision,nullif(trim(coalesce(p_comments,'')),''),now())
  ON CONFLICT(pass_id,approver_role) DO UPDATE
  SET decision=excluded.decision,comments=excluded.comments,decided_at=excluded.decided_at;

  SELECT coalesce((setting_value #>> '{}')::boolean,false) INTO v_holiday
  FROM public.system_settings WHERE setting_key='school_holiday_mode';

  IF p_decision='cancelled' THEN
    v_new:='cancelled';
    UPDATE public.gate_passes
    SET status=v_new,cancelled_at=now(),cancelled_by_role='administrator',
        cancellation_reason=nullif(trim(coalesce(p_comments,'')),''),updated_at=now()
    WHERE id=p_pass_id;
  ELSIF p_decision='rejected' THEN
    v_new:='rejected';
    UPDATE public.gate_passes SET status=v_new,updated_at=now() WHERE id=p_pass_id;
  ELSE
    SELECT exists(SELECT 1 FROM public.gate_pass_approvals
      WHERE pass_id=p_pass_id AND approver_role='administrator' AND decision='approved') INTO v_admin;
    SELECT exists(SELECT 1 FROM public.gate_pass_approvals
      WHERE pass_id=p_pass_id AND approver_role IN ('principal','dean','director') AND decision='approved') INTO v_senior;

    IF v_admin AND (v_holiday OR v_senior) THEN
      v_new:='approved';
      UPDATE public.gate_passes
      SET status='approved',final_approved_at=coalesce(final_approved_at,now()),updated_at=now()
      WHERE id=p_pass_id;
    ELSE
      v_new:='pending';
      UPDATE public.gate_passes SET status='pending',updated_at=now() WHERE id=p_pass_id;
    END IF;
  END IF;

  INSERT INTO public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
  VALUES(p_pass_id,v_old,v_new,'administrator',nullif(trim(coalesce(p_comments,'')),''));
  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('gate_pass','gate_pass',p_pass_id::text,'administrator',p_decision,
    jsonb_build_object('previous_status',v_old,'new_status',v_new,'comments',p_comments,'school_holiday_mode',v_holiday));

  RETURN jsonb_build_object('status','success','pass_id',p_pass_id,'pass_status',v_new,
    'actor_role','administrator','decision',p_decision,'school_holiday_mode',v_holiday);
END;
$$;

-- 8. Admin dashboard includes the full Management data plus term fees.
CREATE OR REPLACE FUNCTION public.admin_services_dashboard(
  p_pin text,
  p_term_id bigint DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_base jsonb;
  v_students jsonb;
  v_terms jsonb;
  v_settings jsonb;
  v_selected public.academic_terms%rowtype;
  v_paid integer;
  v_unpaid integer;
BEGIN
  IF p_pin<>'1972' THEN
    RETURN jsonb_build_object('status','unauthorized','message','School Administration password required.');
  END IF;

  IF p_term_id IS NOT NULL THEN
    SELECT * INTO v_selected FROM public.academic_terms WHERE id=p_term_id;
  ELSE
    SELECT * INTO v_selected FROM public.academic_terms
    ORDER BY is_current DESC,academic_year DESC,term_number DESC LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('status','configuration_error','message','No academic term is configured.');
  END IF;

  v_base:=public.student_services_dashboard('0593');
  IF coalesce(v_base->>'status','')<>'success' THEN RETURN v_base; END IF;

  SELECT coalesce(jsonb_agg(
    x.student_json || jsonb_build_object(
      'fees_paid',coalesce(f.fees_paid,true),
      'fee_notes',f.notes,
      'fee_updated_at',f.updated_at
    ) ORDER BY x.student_json->>'student_name'
  ),'[]'::jsonb)
  INTO v_students
  FROM (
    SELECT value AS student_json
    FROM jsonb_array_elements(v_base->'students')
  ) x
  JOIN public.students s
    ON s.registration_number=(x.student_json->>'registration_number')::bigint
  LEFT JOIN public.student_term_fee_status f
    ON f.student_id=s.id AND f.term_id=v_selected.id;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'id',id,'academic_year',academic_year,'term_number',term_number,
    'term_name',term_name,'fees_due_date',fees_due_date,'is_current',is_current
  ) ORDER BY academic_year DESC,term_number),'[]'::jsonb)
  INTO v_terms
  FROM public.academic_terms;

  SELECT count(*) FILTER(WHERE coalesce(f.fees_paid,true)),
         count(*) FILTER(WHERE NOT coalesce(f.fees_paid,true))
  INTO v_paid,v_unpaid
  FROM public.students s
  LEFT JOIN public.student_term_fee_status f
    ON f.student_id=s.id AND f.term_id=v_selected.id
  WHERE s.is_active=true;

  SELECT coalesce(jsonb_object_agg(setting_key,setting_value),'{}'::jsonb)
  INTO v_settings FROM public.system_settings;

  RETURN v_base || jsonb_build_object(
    'status','success','access_level','administrator','can_review_passes',true,
    'can_manage_settings',true,'can_manage_fees',true,
    'students',v_students,'terms',v_terms,
    'selected_term',jsonb_build_object(
      'id',v_selected.id,'academic_year',v_selected.academic_year,
      'term_number',v_selected.term_number,'term_name',v_selected.term_name,
      'fees_due_date',v_selected.fees_due_date,'is_current',v_selected.is_current
    ),
    'fee_summary',jsonb_build_object('paid',v_paid,'unpaid',v_unpaid,'total',v_paid+v_unpaid),
    'settings',v_settings
  );
END;
$$;

-- 9. Admin can mark fees paid or not paid for a selected term.
CREATE OR REPLACE FUNCTION public.admin_update_fee_status(
  p_pin text,
  p_registration_number text,
  p_term_id bigint,
  p_fees_paid boolean,
  p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_student public.students%rowtype;
  v_term public.academic_terms%rowtype;
BEGIN
  IF p_pin<>'1972' THEN RETURN jsonb_build_object('status','unauthorized','message','School Administration password required.'); END IF;

  SELECT * INTO v_student FROM public.students
  WHERE registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    AND is_active=true LIMIT 1;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found','message','Student not found.'); END IF;

  SELECT * INTO v_term FROM public.academic_terms WHERE id=p_term_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found','message','Academic term not found.'); END IF;

  INSERT INTO public.student_term_fee_status(student_id,term_id,fees_paid,notes,updated_by_role,updated_at)
  VALUES(v_student.id,v_term.id,coalesce(p_fees_paid,false),nullif(trim(coalesce(p_notes,'')),''),'administrator',now())
  ON CONFLICT(student_id,term_id) DO UPDATE
  SET fees_paid=excluded.fees_paid,notes=excluded.notes,updated_by_role='administrator',updated_at=now();

  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('fees','student',v_student.id,'administrator','fee_status_updated',
    jsonb_build_object('registration_number',v_student.registration_number,'term_id',v_term.id,
      'term_name',v_term.term_name,'fees_paid',coalesce(p_fees_paid,false),'notes',p_notes));

  RETURN jsonb_build_object('status','success','student_name',v_student.full_name,
    'registration_number',v_student.registration_number,'term_id',v_term.id,
    'term_name',v_term.term_name,'fees_paid',coalesce(p_fees_paid,false));
END;
$$;

-- 10. Admin-only settings, including School Holiday Mode.
CREATE OR REPLACE FUNCTION public.admin_update_setting(
  p_pin text,
  p_setting_key text,
  p_setting_value jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_holiday boolean;
  v_pass record;
  v_changed integer := 0;
BEGIN
  IF p_pin<>'1972' THEN RETURN jsonb_build_object('status','unauthorized','message','School Administration password required.'); END IF;
  IF p_setting_key NOT IN (
    'school_holiday_mode','gate_pass_pilot_mode','gate_pass_pilot_started_at',
    'gate_pass_pilot_ends_at','gate_terminal_result_seconds'
  ) THEN
    RETURN jsonb_build_object('status','invalid','message','This setting cannot be changed from the Admin site.');
  END IF;

  INSERT INTO public.system_settings(setting_key,setting_value,updated_at)
  VALUES(p_setting_key,p_setting_value,now())
  ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=now();

  IF p_setting_key='school_holiday_mode' THEN
    v_holiday:=coalesce((p_setting_value #>> '{}')::boolean,false);
    IF v_holiday THEN
      FOR v_pass IN
        SELECT p.id,p.status
        FROM public.gate_passes p
        WHERE p.status='pending'
          AND EXISTS(SELECT 1 FROM public.gate_pass_approvals a
            WHERE a.pass_id=p.id AND a.approver_role='administrator' AND a.decision='approved')
      LOOP
        UPDATE public.gate_passes
        SET status='approved',final_approved_at=coalesce(final_approved_at,now()),updated_at=now()
        WHERE id=v_pass.id;
        INSERT INTO public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
        VALUES(v_pass.id,v_pass.status,'approved','administrator','Automatically approved when School Holiday Mode was enabled because Administrator approval already existed.');
        v_changed:=v_changed+1;
      END LOOP;
    END IF;
  END IF;

  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('settings','system_setting',p_setting_key,'administrator','updated',
    jsonb_build_object('value',p_setting_value,'passes_auto_approved',v_changed));

  RETURN jsonb_build_object('status','success','setting_key',p_setting_key,
    'setting_value',p_setting_value,'passes_auto_approved',v_changed);
END;
$$;

-- 11. The Admin site can use the existing operational edit and export functions.
CREATE OR REPLACE FUNCTION public.dashboard_update_student_campus_status(
  p_pin text,
  p_registration_number text,
  p_direction text,
  p_note text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_access_level text;
  v_student public.students%rowtype;
  v_device_id uuid;
  v_last_direction text;
  v_direction text:=upper(trim(coalesce(p_direction,'')));
BEGIN
  v_access_level:=CASE
    WHEN p_pin='1972' THEN 'administrator'
    WHEN p_pin='0593' THEN 'management'
    WHEN p_pin='1960' THEN 'student_leadership'
    ELSE NULL END;
  IF v_access_level IS NULL THEN RETURN jsonb_build_object('status','unauthorized','message','Incorrect password.'); END IF;
  IF v_direction NOT IN ('IN','OUT') THEN RETURN jsonb_build_object('status','invalid','message','Choose On Campus or Off Campus.'); END IF;

  SELECT * INTO v_student FROM public.students
  WHERE registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    AND is_active=true LIMIT 1;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found','message','Student not found.'); END IF;

  SELECT id INTO v_device_id FROM public.gate_devices WHERE is_active=true ORDER BY created_at NULLS LAST LIMIT 1;
  IF v_device_id IS NULL THEN RETURN jsonb_build_object('status','configuration_error','message','No active gate device is configured.'); END IF;

  SELECT direction INTO v_last_direction FROM public.campus_movements
  WHERE student_id=v_student.id ORDER BY scanned_at DESC,id DESC LIMIT 1;
  IF v_last_direction IS NOT DISTINCT FROM v_direction THEN
    RETURN jsonb_build_object('status','same_status','message',CASE WHEN v_direction='IN'
      THEN 'Student is already marked on campus.' ELSE 'Student is already marked off campus.' END,
      'student_name',v_student.full_name,'registration_number',v_student.registration_number,'direction',v_direction);
  END IF;

  INSERT INTO public.campus_movements(student_id,direction,gate_device_id,movement_source,corrected_by,correction_note)
  VALUES(v_student.id,v_direction,v_device_id,'administrative_update',v_access_level,
    coalesce(nullif(trim(coalesce(p_note,'')),''),'Campus status updated from a dashboard.'));
  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('campus_status','student',v_student.id,v_access_level,
    CASE WHEN v_direction='IN' THEN 'marked_on_campus' ELSE 'marked_off_campus' END,
    jsonb_build_object('registration_number',v_student.registration_number,'note',p_note));

  RETURN jsonb_build_object('status','success','message',CASE WHEN v_direction='IN'
    THEN 'Student marked on campus.' ELSE 'Student marked off campus.' END,
    'student_name',v_student.full_name,'registration_number',v_student.registration_number,
    'direction',v_direction,'access_level',v_access_level);
END;
$$;

CREATE OR REPLACE FUNCTION public.dashboard_update_student_accommodation(
  p_pin text,
  p_registration_number text,
  p_residence text,
  p_room text DEFAULT NULL,
  p_bed text DEFAULT NULL,
  p_allocation_status text DEFAULT 'allocated',
  p_remove boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_access_level text;
  v_student public.students%rowtype;
  v_status text:=lower(trim(coalesce(p_allocation_status,'allocated')));
  v_updated integer;
BEGIN
  v_access_level:=CASE
    WHEN p_pin='1972' THEN 'administrator'
    WHEN p_pin='0593' THEN 'management'
    WHEN p_pin='1960' THEN 'student_leadership'
    ELSE NULL END;
  IF v_access_level IS NULL THEN RETURN jsonb_build_object('status','unauthorized','message','Incorrect password.'); END IF;

  SELECT * INTO v_student FROM public.students
  WHERE registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    AND is_active=true LIMIT 1;
  IF NOT FOUND THEN RETURN jsonb_build_object('status','not_found','message','Student not found.'); END IF;

  IF coalesce(p_remove,false) THEN
    UPDATE public.accommodation_allocations
    SET is_active=false,allocation_status='cancelled',ended_at=now(),updated_at=now(),
        notes=concat_ws(' ',nullif(notes,''),'Removed from a dashboard.')
    WHERE student_id=v_student.id AND is_active=true;
    GET DIAGNOSTICS v_updated=ROW_COUNT;
    INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
    VALUES('accommodation','student',v_student.id,v_access_level,'accommodation_removed',
      jsonb_build_object('registration_number',v_student.registration_number,'rows_updated',v_updated));
    RETURN jsonb_build_object('status','success','message','Accommodation removed.',
      'student_name',v_student.full_name,'registration_number',v_student.registration_number,'removed',true);
  END IF;

  IF nullif(trim(coalesce(p_residence,'')),'') IS NULL THEN
    RETURN jsonb_build_object('status','invalid','message','Enter a residence or choose Remove accommodation.');
  END IF;
  IF v_status NOT IN ('waiting','allocated','checked_in','checked_out','cancelled') THEN
    RETURN jsonb_build_object('status','invalid','message','Choose a valid accommodation status.');
  END IF;

  UPDATE public.accommodation_allocations
  SET residence=trim(p_residence),room=nullif(trim(coalesce(p_room,'')),''),
      bed=nullif(trim(coalesce(p_bed,'')),''),allocation_status=v_status,
      allocated_by_role=v_access_level,updated_at=now(),
      ended_at=CASE WHEN v_status='cancelled' THEN now() ELSE NULL END,
      is_active=(v_status<>'cancelled')
  WHERE student_id=v_student.id AND is_active=true;
  GET DIAGNOSTICS v_updated=ROW_COUNT;

  IF v_updated=0 AND v_status<>'cancelled' THEN
    INSERT INTO public.accommodation_allocations(student_id,residence,room,bed,allocation_status,is_active,allocated_by_role,allocated_at,updated_at)
    VALUES(v_student.id,trim(p_residence),nullif(trim(coalesce(p_room,'')),''),
      nullif(trim(coalesce(p_bed,'')),''),v_status,true,v_access_level,now(),now());
  END IF;

  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('accommodation','student',v_student.id,v_access_level,'accommodation_updated',
    jsonb_build_object('registration_number',v_student.registration_number,'residence',trim(p_residence),
      'room',nullif(trim(coalesce(p_room,'')),''),'bed',nullif(trim(coalesce(p_bed,'')),''),'allocation_status',v_status));

  RETURN jsonb_build_object('status','success','message','Accommodation updated.',
    'student_name',v_student.full_name,'registration_number',v_student.registration_number,
    'residence',trim(p_residence),'room',nullif(trim(coalesce(p_room,'')),''),
    'bed',nullif(trim(coalesce(p_bed,'')),''),'allocation_status',v_status,'access_level',v_access_level);
END;
$$;

-- 12. Include the Admin password in report exports.
CREATE OR REPLACE FUNCTION public.student_services_export(
  p_pin text,
  p_report text,
  p_start_date date,
  p_end_date date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE v_result jsonb;
BEGIN
  IF p_pin NOT IN ('1972','0593','1960') THEN RETURN jsonb_build_object('status','unauthorized','message','Incorrect password.'); END IF;
  IF p_start_date IS NULL THEN p_start_date:=current_date-30; END IF;
  IF p_end_date IS NULL THEN p_end_date:=current_date; END IF;
  IF p_report='campus' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(q) ORDER BY q.scanned_at DESC),'[]'::jsonb) INTO v_result FROM (
      SELECT cm.scanned_at,s.registration_number,s.full_name,cm.direction,cm.movement_source,gd.device_name,
             cm.gate_pass_id,cm.checkout_destination_code,cm.checkout_destination_label
      FROM public.campus_movements cm JOIN public.students s ON s.id=cm.student_id
      JOIN public.gate_devices gd ON gd.id=cm.gate_device_id
      WHERE (cm.scanned_at AT TIME ZONE 'Africa/Harare')::date BETWEEN p_start_date AND p_end_date
    ) q;
  ELSIF p_report='passes' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(q) ORDER BY q.submitted_at DESC),'[]'::jsonb) INTO v_result FROM (
      SELECT p.submitted_at,s.registration_number,s.full_name,p.destination,p.reason,p.departure_at,
             p.expected_return_at,p.status,p.final_approved_at,p.actual_departure_at,p.actual_return_at,p.contact_details
      FROM public.gate_passes p JOIN public.students s ON s.id=p.student_id
      WHERE (p.submitted_at AT TIME ZONE 'Africa/Harare')::date BETWEEN p_start_date AND p_end_date
    ) q;
  ELSIF p_report='gate_duty' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(q) ORDER BY q.scanned_at DESC),'[]'::jsonb) INTO v_result FROM (
      SELECT g.scanned_at,s.registration_number,s.full_name,g.direction,g.record_source,gd.device_name
      FROM public.gate_duty_records g JOIN public.students s ON s.id=g.student_id
      JOIN public.gate_devices gd ON gd.id=g.gate_device_id
      WHERE (g.scanned_at AT TIME ZONE 'Africa/Harare')::date BETWEEN p_start_date AND p_end_date
    ) q;
  ELSIF p_report='meals' THEN
    SELECT coalesce(jsonb_agg(to_jsonb(q) ORDER BY q.checked_in_at DESC),'[]'::jsonb) INTO v_result FROM (
      SELECT c.service_date,c.checked_in_at,s.registration_number,s.full_name,c.meal_session,c.check_in_source
      FROM public.check_ins c JOIN public.students s ON s.id=c.student_id
      WHERE c.service_date BETWEEN p_start_date AND p_end_date
    ) q;
  ELSE RETURN jsonb_build_object('status','invalid','message','Unknown report type.'); END IF;
  RETURN jsonb_build_object('status','success','report',p_report,'rows',v_result);
END;
$$;

CREATE OR REPLACE FUNCTION public.student_movements_export(p_pin text,p_period text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_period text:=lower(trim(coalesce(p_period,'current_status')));
  v_start timestamptz;
  v_label text;
  v_rows jsonb;
  v_total integer; v_on_campus integer; v_bed_rest integer; v_on_gate_pass integer;
BEGIN
  IF p_pin NOT IN ('1972','0593','1960') THEN RETURN jsonb_build_object('status','unauthorized','message','Incorrect password.'); END IF;
  CASE v_period
    WHEN 'current_status' THEN v_start:=NULL;v_label:='Current status';
    WHEN 'last_24_hours' THEN v_start:=now()-interval '24 hours';v_label:='Last 24 hours';
    WHEN 'last_3_days' THEN v_start:=now()-interval '3 days';v_label:='Last 3 days';
    WHEN 'past_week' THEN v_start:=now()-interval '7 days';v_label:='Past week';
    ELSE RETURN jsonb_build_object('status','invalid','message','Choose current_status, last_24_hours, last_3_days or past_week.');
  END CASE;

  WITH latest_all AS (
    SELECT DISTINCT ON (cm.student_id) cm.student_id,cm.direction,cm.scanned_at,cm.checkout_destination_label,cm.gate_pass_id
    FROM public.campus_movements cm ORDER BY cm.student_id,cm.scanned_at DESC,cm.id DESC
  ), period_stats AS (
    SELECT cm.student_id,count(*)::integer movement_count,max(cm.scanned_at) last_movement_at
    FROM public.campus_movements cm WHERE v_start IS NOT NULL AND cm.scanned_at>=v_start GROUP BY cm.student_id
  ), period_last AS (
    SELECT DISTINCT ON (cm.student_id) cm.student_id,cm.direction,cm.scanned_at,cm.checkout_destination_label
    FROM public.campus_movements cm WHERE v_start IS NULL OR cm.scanned_at>=v_start
    ORDER BY cm.student_id,cm.scanned_at DESC,cm.id DESC
  ), active_bed_rest AS (
    SELECT DISTINCT ON (x.student_id) x.student_id,x.started_at,x.notes
    FROM public.student_support_statuses x WHERE x.status_type='bed_rest' AND x.is_active=true
    ORDER BY x.student_id,x.started_at DESC,x.id DESC
  ), active_maternity AS (
    SELECT DISTINCT ON (x.student_id) x.student_id,x.started_at
    FROM public.student_support_statuses x WHERE x.status_type='maternity' AND x.is_active=true
    ORDER BY x.student_id,x.started_at DESC,x.id DESC
  ), current_pass AS (
    SELECT DISTINCT ON (p.student_id) p.student_id,p.id,p.status,p.destination,p.departure_at,
      p.expected_return_at,p.actual_departure_at,(p.status='departed' AND p.expected_return_at<now()) overdue
    FROM public.gate_passes p WHERE p.status IN ('departed','approved')
    ORDER BY p.student_id,CASE WHEN p.status='departed' THEN 0 ELSE 1 END,
      coalesce(p.actual_departure_at,p.departure_at) DESC,p.submitted_at DESC
  ), current_accommodation AS (
    SELECT DISTINCT ON (a.student_id) a.student_id,a.residence,a.room,a.bed
    FROM public.accommodation_allocations a WHERE a.is_active=true
    ORDER BY a.student_id,a.allocated_at DESC,a.id DESC
  ), report_rows AS (
    SELECT s.registration_number,s.full_name student_name,
      CASE coalesce(la.direction,'UNKNOWN') WHEN 'IN' THEN 'On Campus' WHEN 'OUT' THEN 'Off Campus' ELSE 'Unknown' END current_campus_status,
      CASE WHEN la.direction='IN' THEN 'Yes' ELSE 'No' END on_campus,
      la.scanned_at latest_movement_at,la.direction latest_movement_direction,
      coalesce(la.checkout_destination_label,'') latest_checkout_destination,
      CASE WHEN br.student_id IS NOT NULL THEN 'Yes' ELSE 'No' END on_bed_rest,
      br.started_at bed_rest_started_at,CASE WHEN mat.student_id IS NOT NULL THEN 'Yes' ELSE 'No' END maternity,
      CASE WHEN cp.status='departed' THEN 'Yes' ELSE 'No' END on_gate_pass,
      coalesce(initcap(cp.status),'None') gate_pass_status,coalesce(cp.destination,'') gate_pass_destination,
      cp.departure_at gate_pass_departure_at,cp.expected_return_at gate_pass_expected_return_at,
      CASE WHEN coalesce(cp.overdue,false) THEN 'Yes' ELSE 'No' END gate_pass_overdue,
      CASE WHEN v_period='current_status' THEN NULL ELSE coalesce(ps.movement_count,0) END movements_in_period,
      CASE WHEN v_period='current_status' THEN la.scanned_at ELSE pl.scanned_at END last_movement_in_period,
      CASE WHEN v_period='current_status' THEN la.direction ELSE pl.direction END last_direction_in_period,
      CASE WHEN v_period='current_status' THEN coalesce(la.checkout_destination_label,'') ELSE coalesce(pl.checkout_destination_label,'') END last_destination_in_period,
      coalesce(ca.residence,'') residence,coalesce(ca.room,'') room,coalesce(ca.bed,'') bed
    FROM public.students s
    LEFT JOIN latest_all la ON la.student_id=s.id
    LEFT JOIN period_stats ps ON ps.student_id=s.id
    LEFT JOIN period_last pl ON pl.student_id=s.id
    LEFT JOIN active_bed_rest br ON br.student_id=s.id
    LEFT JOIN active_maternity mat ON mat.student_id=s.id
    LEFT JOIN current_pass cp ON cp.student_id=s.id
    LEFT JOIN current_accommodation ca ON ca.student_id=s.id
    WHERE s.is_active=true
  )
  SELECT count(*)::integer,count(*) FILTER(WHERE on_campus='Yes')::integer,
    count(*) FILTER(WHERE on_bed_rest='Yes')::integer,count(*) FILTER(WHERE on_gate_pass='Yes')::integer,
    coalesce(jsonb_agg(to_jsonb(report_rows) ORDER BY
      CASE WHEN on_gate_pass='Yes' THEN 0 ELSE 1 END,
      CASE WHEN on_bed_rest='Yes' THEN 0 ELSE 1 END,
      CASE WHEN on_campus='Yes' THEN 0 ELSE 1 END,student_name),'[]'::jsonb)
  INTO v_total,v_on_campus,v_bed_rest,v_on_gate_pass,v_rows FROM report_rows;

  INSERT INTO public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  VALUES('report_export','student_movements',v_period,
    CASE WHEN p_pin='1972' THEN 'administrator' WHEN p_pin='0593' THEN 'management' ELSE 'student_leadership' END,
    'exported',jsonb_build_object('period',v_period,'period_start',v_start,'row_count',v_total));

  RETURN jsonb_build_object('status','success','report','student_movements','period',v_period,
    'period_label',v_label,'period_start',v_start,'generated_at',now(),
    'summary',jsonb_build_object('active_students',v_total,'on_campus',v_on_campus,
      'on_bed_rest',v_bed_rest,'on_gate_pass',v_on_gate_pass),'rows',v_rows);
END;
$$;

GRANT EXECUTE ON FUNCTION public.admin_services_dashboard(text,bigint) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.admin_gate_pass_decision(text,uuid,text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_fee_status(text,text,bigint,boolean,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_setting(text,text,jsonb) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.student_submit_gate_pass(text,text,text,timestamptz,timestamptz,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.student_gate_pass_status(text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.student_services_dashboard(text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.dashboard_gate_pass_decision(text,uuid,text,text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.dashboard_update_student_campus_status(text,text,text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.dashboard_update_student_accommodation(text,text,text,text,text,text,boolean) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.student_services_export(text,text,date,date) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.student_movements_export(text,text) TO anon,authenticated;
