-- AMFCC Student Services Platform v2 database migration
-- Adds digital gate passes, gate duty, settings, audit history and dashboard RPCs.

create extension if not exists pgcrypto;

create table if not exists public.system_settings (
  setting_key text primary key,
  setting_value jsonb not null,
  description text,
  updated_at timestamptz not null default now()
);

insert into public.system_settings(setting_key, setting_value, description)
values
  ('school_timezone', '"Africa/Harare"'::jsonb, 'Timezone used for deadlines and reporting.'),
  ('gate_pass_pilot_mode', 'true'::jsonb, 'When true, electronic gate passes run alongside paper passes.'),
  ('gate_pass_pilot_started_at', to_jsonb(now()), 'Date and time the one-week paper/electronic pilot started.'),
  ('gate_pass_pilot_ends_at', to_jsonb(now() + interval '7 days'), 'Planned end of the paper/electronic pilot.'),
  ('gate_pass_deadline_day', '3'::jsonb, 'ISO weekday for the weekly gate-pass deadline. Wednesday is 3.'),
  ('gate_pass_deadline_time', '"16:00"'::jsonb, 'Weekly gate-pass submission deadline in local school time.'),
  ('gate_terminal_result_seconds', '2.4'::jsonb, 'Seconds a scan result stays on the kiosk screen.')
on conflict (setting_key) do nothing;

create table if not exists public.gate_passes (
  id uuid primary key default gen_random_uuid(),
  student_id text not null references public.students(id) on delete restrict,
  destination text not null,
  reason text not null,
  departure_at timestamptz not null,
  expected_return_at timestamptz not null,
  contact_details text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','cancelled','departed','returned','expired')),
  submitted_at timestamptz not null default now(),
  final_approved_at timestamptz,
  actual_departure_at timestamptz,
  actual_return_at timestamptz,
  paper_pass_checked boolean not null default false,
  cancelled_at timestamptz,
  cancelled_by_role text,
  cancellation_reason text,
  created_source text not null default 'student' check (created_source in ('student','staff','emergency_override')),
  updated_at timestamptz not null default now(),
  check (expected_return_at > departure_at)
);

create table if not exists public.gate_pass_approvals (
  id bigint generated by default as identity primary key,
  pass_id uuid not null references public.gate_passes(id) on delete cascade,
  approver_role text not null check (approver_role in ('administrator','principal','dean','director')),
  decision text not null check (decision in ('approved','rejected','cancelled')),
  comments text,
  decided_at timestamptz not null default now(),
  unique(pass_id, approver_role)
);

create table if not exists public.gate_pass_status_history (
  id bigint generated by default as identity primary key,
  pass_id uuid not null references public.gate_passes(id) on delete cascade,
  previous_status text,
  new_status text not null,
  actor_role text,
  notes text,
  changed_at timestamptz not null default now()
);

create table if not exists public.gate_duty_records (
  id bigint generated by default as identity primary key,
  student_id text not null references public.students(id) on delete restrict,
  direction text not null check (direction in ('IN','OUT')),
  scanned_at timestamptz not null default now(),
  gate_device_id uuid not null references public.gate_devices(id) on delete restrict,
  record_source text not null default 'scanner' check (record_source in ('scanner','manual'))
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  event_type text not null,
  entity_type text not null,
  entity_id text,
  actor_role text,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.campus_movements add column if not exists gate_pass_id uuid references public.gate_passes(id) on delete set null;

create index if not exists gate_passes_student_idx on public.gate_passes(student_id, submitted_at desc);
create index if not exists gate_passes_status_idx on public.gate_passes(status, departure_at);
create index if not exists gate_pass_approvals_pass_idx on public.gate_pass_approvals(pass_id, decided_at);
create index if not exists gate_pass_history_pass_idx on public.gate_pass_status_history(pass_id, changed_at);
create index if not exists gate_duty_student_idx on public.gate_duty_records(student_id, scanned_at desc);
create index if not exists gate_duty_time_idx on public.gate_duty_records(scanned_at desc);
create index if not exists campus_movements_pass_idx on public.campus_movements(gate_pass_id);
create index if not exists audit_log_entity_idx on public.audit_log(entity_type, entity_id, created_at desc);

alter table public.system_settings enable row level security;
alter table public.gate_passes enable row level security;
alter table public.gate_pass_approvals enable row level security;
alter table public.gate_pass_status_history enable row level security;
alter table public.gate_duty_records enable row level security;
alter table public.audit_log enable row level security;

revoke all on public.system_settings, public.gate_passes, public.gate_pass_approvals, public.gate_pass_status_history, public.gate_duty_records, public.audit_log from anon, authenticated;

create or replace function public._gate_pass_deadline(p_departure_at timestamptz)
returns timestamptz
language plpgsql
stable
set search_path = public
as $$
declare
  v_local timestamp;
  v_monday timestamp;
  v_deadline_local timestamp;
  v_dow integer;
begin
  v_local := p_departure_at at time zone 'Africa/Harare';
  v_monday := date_trunc('week', v_local);
  v_dow := extract(isodow from v_local)::integer;
  if v_dow between 1 and 3 then
    v_deadline_local := v_monday - interval '5 days' + interval '16 hours';
  else
    v_deadline_local := v_monday + interval '2 days 16 hours';
  end if;
  return v_deadline_local at time zone 'Africa/Harare';
end;
$$;

create or replace function public.student_submit_gate_pass(
  p_registration_number text,
  p_destination text,
  p_reason text,
  p_departure_at timestamptz,
  p_expected_return_at timestamptz,
  p_contact_details text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student public.students%rowtype;
  v_pass public.gate_passes%rowtype;
  v_deadline timestamptz;
  v_pilot boolean;
  v_pilot_end jsonb;
begin
  select * into v_student
  from public.students
  where registration_number::text = regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    and is_active = true
  limit 1;

  if not found then
    return jsonb_build_object('status','not_found','message','Student registration number was not found.');
  end if;

  if length(trim(coalesce(p_destination,''))) < 2
     or length(trim(coalesce(p_reason,''))) < 3
     or length(trim(coalesce(p_contact_details,''))) < 3 then
    return jsonb_build_object('status','invalid','message','Complete the destination, reason and contact details.');
  end if;

  if p_departure_at is null or p_expected_return_at is null or p_expected_return_at <= p_departure_at then
    return jsonb_build_object('status','invalid','message','Expected return must be later than departure.');
  end if;

  if p_departure_at <= now() then
    return jsonb_build_object('status','invalid','message','Departure must be in the future.');
  end if;

  v_deadline := public._gate_pass_deadline(p_departure_at);
  if now() > v_deadline then
    return jsonb_build_object(
      'status','deadline_closed',
      'message','The Wednesday 4:00 pm submission deadline has passed. Contact the School Administrator for an emergency request.',
      'deadline',v_deadline
    );
  end if;

  if exists (
    select 1 from public.gate_passes
    where student_id = v_student.id
      and status in ('pending','approved','departed')
      and tstzrange(departure_at, expected_return_at, '[]') && tstzrange(p_departure_at, p_expected_return_at, '[]')
  ) then
    return jsonb_build_object('status','duplicate_request','message','An active gate pass already overlaps this period.');
  end if;

  insert into public.gate_passes(student_id,destination,reason,departure_at,expected_return_at,contact_details)
  values(v_student.id,trim(p_destination),trim(p_reason),p_departure_at,p_expected_return_at,trim(p_contact_details))
  returning * into v_pass;

  insert into public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
  values(v_pass.id,null,'pending','student','Gate pass submitted.');

  insert into public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  values('gate_pass','gate_pass',v_pass.id::text,'student','submitted',jsonb_build_object('student_id',v_student.id,'registration_number',v_student.registration_number));

  select coalesce((setting_value #>> '{}')::boolean,false) into v_pilot
  from public.system_settings where setting_key='gate_pass_pilot_mode';
  select setting_value into v_pilot_end from public.system_settings where setting_key='gate_pass_pilot_ends_at';

  return jsonb_build_object(
    'status','success',
    'pass_id',v_pass.id,
    'student_name',v_student.full_name,
    'registration_number',v_student.registration_number,
    'pass_status',v_pass.status,
    'deadline',v_deadline,
    'pilot_mode',v_pilot,
    'pilot_ends_at',v_pilot_end
  );
end;
$$;

create or replace function public.student_gate_pass_status(p_registration_number text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student public.students%rowtype;
  v_passes jsonb;
  v_pilot boolean;
  v_pilot_end jsonb;
begin
  select * into v_student
  from public.students
  where registration_number::text = regexp_replace(coalesce(p_registration_number,''),'\D','','g')
    and is_active = true
  limit 1;

  if not found then
    return jsonb_build_object('status','not_found','message','Student registration number was not found.');
  end if;

  select coalesce(jsonb_agg(item order by submitted_at desc),'[]'::jsonb)
  into v_passes
  from (
    select p.submitted_at,
      jsonb_build_object(
        'id',p.id,
        'destination',p.destination,
        'reason',p.reason,
        'departure_at',p.departure_at,
        'expected_return_at',p.expected_return_at,
        'status',p.status,
        'submitted_at',p.submitted_at,
        'final_approved_at',p.final_approved_at,
        'actual_departure_at',p.actual_departure_at,
        'actual_return_at',p.actual_return_at,
        'paper_pass_checked',p.paper_pass_checked,
        'cancellation_reason',p.cancellation_reason,
        'approvals',coalesce((
          select jsonb_agg(jsonb_build_object(
            'role',a.approver_role,
            'decision',a.decision,
            'comments',a.comments,
            'decided_at',a.decided_at
          ) order by a.decided_at)
          from public.gate_pass_approvals a where a.pass_id=p.id
        ),'[]'::jsonb),
        'waiting_on',case
          when p.status <> 'pending' then null
          when not exists(select 1 from public.gate_pass_approvals a where a.pass_id=p.id and a.approver_role='administrator' and a.decision='approved') then 'School Administrator'
          when not exists(select 1 from public.gate_pass_approvals a where a.pass_id=p.id and a.approver_role in ('principal','dean','director') and a.decision='approved') then 'Principal, Dean or Director'
          else null end
      ) item
    from public.gate_passes p
    where p.student_id=v_student.id
    order by p.submitted_at desc
    limit 20
  ) q;

  select coalesce((setting_value #>> '{}')::boolean,false) into v_pilot
  from public.system_settings where setting_key='gate_pass_pilot_mode';
  select setting_value into v_pilot_end from public.system_settings where setting_key='gate_pass_pilot_ends_at';

  return jsonb_build_object(
    'status','success',
    'student_name',v_student.full_name,
    'registration_number',v_student.registration_number,
    'passes',v_passes,
    'pilot_mode',v_pilot,
    'pilot_ends_at',v_pilot_end
  );
end;
$$;

create or replace function public.dashboard_gate_pass_decision(
  p_pin text,
  p_pass_id uuid,
  p_actor_role text,
  p_decision text,
  p_comments text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pass public.gate_passes%rowtype;
  v_old_status text;
  v_new_status text;
  v_admin_ok boolean;
  v_senior_ok boolean;
begin
  if p_pin <> '1960' then
    return jsonb_build_object('status','unauthorized','message','Incorrect PIN.');
  end if;
  if p_actor_role not in ('administrator','principal','dean','director') then
    return jsonb_build_object('status','invalid','message','Choose the approving or rejecting role.');
  end if;
  if p_decision not in ('approved','rejected','cancelled') then
    return jsonb_build_object('status','invalid','message','Choose Approve, Reject or Cancel.');
  end if;

  select * into v_pass from public.gate_passes where id=p_pass_id for update;
  if not found then return jsonb_build_object('status','not_found','message','Gate pass not found.'); end if;
  v_old_status := v_pass.status;

  insert into public.gate_pass_approvals(pass_id,approver_role,decision,comments,decided_at)
  values(p_pass_id,p_actor_role,p_decision,nullif(trim(coalesce(p_comments,'')),''),now())
  on conflict(pass_id,approver_role) do update
    set decision=excluded.decision,comments=excluded.comments,decided_at=excluded.decided_at;

  if p_decision='cancelled' then
    v_new_status:='cancelled';
    update public.gate_passes set status=v_new_status,cancelled_at=now(),cancelled_by_role=p_actor_role,cancellation_reason=nullif(trim(coalesce(p_comments,'')),''),updated_at=now() where id=p_pass_id;
  elsif p_decision='rejected' then
    v_new_status:='rejected';
    update public.gate_passes set status=v_new_status,updated_at=now() where id=p_pass_id;
  else
    select exists(select 1 from public.gate_pass_approvals where pass_id=p_pass_id and approver_role='administrator' and decision='approved') into v_admin_ok;
    select exists(select 1 from public.gate_pass_approvals where pass_id=p_pass_id and approver_role in ('principal','dean','director') and decision='approved') into v_senior_ok;
    if v_admin_ok and v_senior_ok then
      v_new_status:='approved';
      update public.gate_passes set status='approved',final_approved_at=coalesce(final_approved_at,now()),updated_at=now() where id=p_pass_id;
    else
      v_new_status:='pending';
      update public.gate_passes set status='pending',updated_at=now() where id=p_pass_id;
    end if;
  end if;

  insert into public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
  values(p_pass_id,v_old_status,v_new_status,p_actor_role,nullif(trim(coalesce(p_comments,'')),''));
  insert into public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  values('gate_pass','gate_pass',p_pass_id::text,p_actor_role,p_decision,jsonb_build_object('previous_status',v_old_status,'new_status',v_new_status,'comments',p_comments));

  return jsonb_build_object('status','success','pass_id',p_pass_id,'pass_status',v_new_status,'actor_role',p_actor_role,'decision',p_decision);
end;
$$;

create or replace function public.gate_record_movement_v3(
  p_device_token text,
  p_registration_number text,
  p_direction text,
  p_source text default 'scanner'
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_device public.gate_devices%rowtype;
  v_student public.students%rowtype;
  v_last public.campus_movements%rowtype;
  v_pass public.gate_passes%rowtype;
  v_pilot boolean;
  v_pass_message text;
  v_has_pass boolean := false;
begin
  select * into v_device from public.gate_devices
  where token_hash=encode(digest(p_device_token,'sha256'),'hex') and is_active=true;
  if not found then return jsonb_build_object('status','unauthorized','message','This device is not authorised for gate scanning.'); end if;
  if upper(p_direction) not in ('IN','OUT') then return jsonb_build_object('status','invalid_direction','message','Choose IN or OUT.'); end if;
  if p_source not in ('scanner','manual') then p_source:='scanner'; end if;

  select * into v_student from public.students
  where registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g') and is_active=true limit 1;
  if not found then return jsonb_build_object('status','not_found','message','Student not found.'); end if;

  select * into v_last from public.campus_movements where student_id=v_student.id order by scanned_at desc,id desc limit 1;
  if found and v_last.direction=upper(p_direction) then
    if v_last.scanned_at>now()-interval '30 seconds' then
      return jsonb_build_object('status','duplicate','message','Duplicate scan ignored.','student_name',v_student.full_name,'registration_number',v_student.registration_number,'direction',v_last.direction,'last_scanned_at',v_last.scanned_at);
    end if;
    return jsonb_build_object('status','same_status','message',case when upper(p_direction)='IN' then 'Student is already marked on campus.' else 'Student is already marked off campus.' end,'student_name',v_student.full_name,'registration_number',v_student.registration_number,'direction',v_last.direction,'last_scanned_at',v_last.scanned_at);
  end if;

  if upper(p_direction)='OUT' then
    select * into v_pass
    from public.gate_passes
    where student_id=v_student.id and status='approved'
      and departure_at between now()-interval '12 hours' and now()+interval '12 hours'
      and expected_return_at > now()
    order by departure_at
    limit 1
    for update;
    if found then
      update public.gate_passes set status='departed',actual_departure_at=now(),updated_at=now() where id=v_pass.id;
      insert into public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
      values(v_pass.id,'approved','departed','gate_terminal','Student scanned out at the gate.');
      v_has_pass:=true;
      v_pass_message:='Personal gate pass verified.';
    else
      v_pass_message:='Movement recorded. No personal gate pass was linked; this may be a Tanaka or school outing.';
    end if;
  else
    select * into v_pass
    from public.gate_passes
    where student_id=v_student.id and status='departed'
    order by actual_departure_at desc nulls last,departure_at desc
    limit 1
    for update;
    if found then
      update public.gate_passes set status='returned',actual_return_at=now(),updated_at=now() where id=v_pass.id;
      insert into public.gate_pass_status_history(pass_id,previous_status,new_status,actor_role,notes)
      values(v_pass.id,'departed','returned','gate_terminal','Student scanned back in at the gate.');
      v_has_pass:=true;
      v_pass_message:='Return linked to the personal gate pass.';
    else
      v_pass_message:='Campus movement recorded.';
    end if;
  end if;

  insert into public.campus_movements(student_id,direction,gate_device_id,movement_source,gate_pass_id)
  values(v_student.id,upper(p_direction),v_device.id,p_source,case when v_has_pass then v_pass.id else null end);
  update public.gate_devices set last_seen_at=now() where id=v_device.id;

  select coalesce((setting_value #>> '{}')::boolean,false) into v_pilot
  from public.system_settings where setting_key='gate_pass_pilot_mode';

  insert into public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  values('campus_movement','student',v_student.id,'gate_terminal',lower(p_direction),jsonb_build_object('device_id',v_device.id,'source',p_source,'gate_pass_id',case when v_has_pass then v_pass.id else null end));

  return jsonb_build_object(
    'status','success','message',v_pass_message,
    'student_name',v_student.full_name,'registration_number',v_student.registration_number,
    'direction',upper(p_direction),'scanned_at',now(),
    'gate_pass_id',case when v_has_pass then v_pass.id else null end,
    'gate_pass_status',case when v_has_pass then 'verified' else 'not_linked' end,
    'paper_pass_pilot_mode',v_pilot
  );
end;
$$;

create or replace function public.gate_duty_record(
  p_device_token text,
  p_registration_number text,
  p_direction text,
  p_source text default 'scanner'
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_device public.gate_devices%rowtype;
  v_student public.students%rowtype;
  v_last public.gate_duty_records%rowtype;
begin
  select * into v_device from public.gate_devices
  where token_hash=encode(digest(p_device_token,'sha256'),'hex') and is_active=true;
  if not found then return jsonb_build_object('status','unauthorized','message','This device is not authorised for gate scanning.'); end if;
  if upper(p_direction) not in ('IN','OUT') then return jsonb_build_object('status','invalid_direction','message','Choose IN or OUT.'); end if;
  if p_source not in ('scanner','manual') then p_source:='scanner'; end if;

  select * into v_student from public.students
  where registration_number::text=regexp_replace(coalesce(p_registration_number,''),'\D','','g') and is_active=true limit 1;
  if not found then return jsonb_build_object('status','not_found','message','Student not found.'); end if;

  select * into v_last from public.gate_duty_records where student_id=v_student.id order by scanned_at desc,id desc limit 1;
  if found and v_last.direction=upper(p_direction) then
    if v_last.scanned_at>now()-interval '30 seconds' then
      return jsonb_build_object('status','duplicate','message','Duplicate gate-duty scan ignored.','student_name',v_student.full_name,'registration_number',v_student.registration_number,'direction',v_last.direction,'last_scanned_at',v_last.scanned_at);
    end if;
    return jsonb_build_object('status','same_status','message',case when upper(p_direction)='IN' then 'Student is already checked in for gate duty.' else 'Student is already checked out from gate duty.' end,'student_name',v_student.full_name,'registration_number',v_student.registration_number,'direction',v_last.direction,'last_scanned_at',v_last.scanned_at);
  end if;

  insert into public.gate_duty_records(student_id,direction,gate_device_id,record_source)
  values(v_student.id,upper(p_direction),v_device.id,p_source);
  update public.gate_devices set last_seen_at=now() where id=v_device.id;
  insert into public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  values('gate_duty','student',v_student.id,'gate_terminal',lower(p_direction),jsonb_build_object('device_id',v_device.id,'source',p_source));

  return jsonb_build_object('status','success','message',case when upper(p_direction)='IN' then 'Gate duty started.' else 'Gate duty ended.' end,'student_name',v_student.full_name,'registration_number',v_student.registration_number,'direction',upper(p_direction),'scanned_at',now());
end;
$$;

create or replace function public.student_services_dashboard(p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_students jsonb;
  v_recent jsonb;
  v_passes jsonb;
  v_duty jsonb;
  v_settings jsonb;
  v_on integer;
  v_off integer;
  v_unknown integer;
  v_pending integer;
  v_approved integer;
  v_overdue integer;
begin
  if p_pin <> '1960' then return jsonb_build_object('status','unauthorized','message','Incorrect PIN.'); end if;

  with latest as (
    select distinct on (cm.student_id) cm.student_id,cm.direction,cm.scanned_at,gd.device_name,gd.location
    from public.campus_movements cm join public.gate_devices gd on gd.id=cm.gate_device_id
    order by cm.student_id,cm.scanned_at desc,cm.id desc
  ), roster as (
    select s.id,s.registration_number,s.full_name,coalesce(l.direction,'UNKNOWN') status,l.scanned_at,l.device_name,l.location
    from public.students s left join latest l on l.student_id=s.id where s.is_active=true
  )
  select count(*) filter(where status='IN'),count(*) filter(where status='OUT'),count(*) filter(where status='UNKNOWN'),
         coalesce(jsonb_agg(jsonb_build_object('student_id',id,'registration_number',registration_number,'student_name',full_name,'status',status,'last_movement_at',scanned_at,'device_name',device_name,'location',location) order by full_name),'[]'::jsonb)
  into v_on,v_off,v_unknown,v_students from roster;

  select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'registration_number',x.registration_number,'student_name',x.full_name,'direction',x.direction,'scanned_at',x.scanned_at,'device_name',x.device_name,'location',x.location,'gate_pass_id',x.gate_pass_id) order by x.scanned_at desc),'[]'::jsonb)
  into v_recent
  from (
    select cm.id,s.registration_number,s.full_name,cm.direction,cm.scanned_at,gd.device_name,gd.location,cm.gate_pass_id
    from public.campus_movements cm join public.students s on s.id=cm.student_id join public.gate_devices gd on gd.id=cm.gate_device_id
    order by cm.scanned_at desc,cm.id desc limit 150
  ) x;

  select count(*) filter(where status='pending'),count(*) filter(where status='approved'),count(*) filter(where status='departed' and expected_return_at<now())
  into v_pending,v_approved,v_overdue from public.gate_passes;

  select coalesce(jsonb_agg(item order by submitted_at desc),'[]'::jsonb) into v_passes
  from (
    select p.submitted_at,
      jsonb_build_object(
        'id',p.id,'student_id',p.student_id,'student_name',s.full_name,'registration_number',s.registration_number,
        'destination',p.destination,'reason',p.reason,'contact_details',p.contact_details,
        'departure_at',p.departure_at,'expected_return_at',p.expected_return_at,'submitted_at',p.submitted_at,
        'status',p.status,'final_approved_at',p.final_approved_at,'actual_departure_at',p.actual_departure_at,'actual_return_at',p.actual_return_at,
        'paper_pass_checked',p.paper_pass_checked,'cancellation_reason',p.cancellation_reason,
        'overdue',(p.status='departed' and p.expected_return_at<now()),
        'approvals',coalesce((select jsonb_agg(jsonb_build_object('role',a.approver_role,'decision',a.decision,'comments',a.comments,'decided_at',a.decided_at) order by a.decided_at) from public.gate_pass_approvals a where a.pass_id=p.id),'[]'::jsonb),
        'waiting_on',case
          when p.status <> 'pending' then null
          when not exists(select 1 from public.gate_pass_approvals a where a.pass_id=p.id and a.approver_role='administrator' and a.decision='approved') then 'School Administrator'
          when not exists(select 1 from public.gate_pass_approvals a where a.pass_id=p.id and a.approver_role in ('principal','dean','director') and a.decision='approved') then 'Principal, Dean or Director'
          else null end
      ) item
    from public.gate_passes p join public.students s on s.id=p.student_id
    order by p.submitted_at desc limit 300
  ) q;

  select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'student_name',x.full_name,'registration_number',x.registration_number,'direction',x.direction,'scanned_at',x.scanned_at,'source',x.record_source) order by x.scanned_at desc),'[]'::jsonb)
  into v_duty
  from (
    select g.id,s.full_name,s.registration_number,g.direction,g.scanned_at,g.record_source
    from public.gate_duty_records g join public.students s on s.id=g.student_id
    where (g.scanned_at at time zone 'Africa/Harare')::date=(now() at time zone 'Africa/Harare')::date
    order by g.scanned_at desc limit 200
  ) x;

  select coalesce(jsonb_object_agg(setting_key,setting_value),'{}'::jsonb) into v_settings from public.system_settings;

  return jsonb_build_object(
    'status','success',
    'counts',jsonb_build_object('on_campus',v_on,'off_campus',v_off,'unknown',v_unknown,'pending_passes',v_pending,'approved_passes',v_approved,'overdue_passes',v_overdue),
    'students',v_students,'recent_movements',v_recent,'gate_passes',v_passes,'gate_duty_today',v_duty,'settings',v_settings
  );
end;
$$;

create or replace function public.student_services_update_setting(p_pin text,p_setting_key text,p_setting_value jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_pin <> '1960' then return jsonb_build_object('status','unauthorized','message','Incorrect PIN.'); end if;
  if p_setting_key not in ('gate_pass_pilot_mode','gate_pass_pilot_started_at','gate_pass_pilot_ends_at','gate_terminal_result_seconds') then
    return jsonb_build_object('status','invalid','message','This setting cannot be changed from the application.');
  end if;
  insert into public.system_settings(setting_key,setting_value,updated_at)
  values(p_setting_key,p_setting_value,now())
  on conflict(setting_key) do update set setting_value=excluded.setting_value,updated_at=now();
  insert into public.audit_log(event_type,entity_type,entity_id,actor_role,action,details)
  values('settings','system_setting',p_setting_key,'administrator','updated',jsonb_build_object('value',p_setting_value));
  return jsonb_build_object('status','success','setting_key',p_setting_key,'setting_value',p_setting_value);
end;
$$;

create or replace function public.student_services_export(p_pin text,p_report text,p_start_date date,p_end_date date)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_result jsonb;
begin
  if p_pin <> '1960' then return jsonb_build_object('status','unauthorized','message','Incorrect PIN.'); end if;
  if p_start_date is null then p_start_date := current_date - 30; end if;
  if p_end_date is null then p_end_date := current_date; end if;

  if p_report='campus' then
    select coalesce(jsonb_agg(to_jsonb(q) order by q.scanned_at desc),'[]'::jsonb) into v_result
    from (select cm.scanned_at,s.registration_number,s.full_name,cm.direction,cm.movement_source,gd.device_name,cm.gate_pass_id
          from public.campus_movements cm join public.students s on s.id=cm.student_id join public.gate_devices gd on gd.id=cm.gate_device_id
          where (cm.scanned_at at time zone 'Africa/Harare')::date between p_start_date and p_end_date) q;
  elsif p_report='passes' then
    select coalesce(jsonb_agg(to_jsonb(q) order by q.submitted_at desc),'[]'::jsonb) into v_result
    from (select p.submitted_at,s.registration_number,s.full_name,p.destination,p.reason,p.departure_at,p.expected_return_at,p.status,p.final_approved_at,p.actual_departure_at,p.actual_return_at,p.contact_details
          from public.gate_passes p join public.students s on s.id=p.student_id
          where (p.submitted_at at time zone 'Africa/Harare')::date between p_start_date and p_end_date) q;
  elsif p_report='gate_duty' then
    select coalesce(jsonb_agg(to_jsonb(q) order by q.scanned_at desc),'[]'::jsonb) into v_result
    from (select g.scanned_at,s.registration_number,s.full_name,g.direction,g.record_source,gd.device_name
          from public.gate_duty_records g join public.students s on s.id=g.student_id join public.gate_devices gd on gd.id=g.gate_device_id
          where (g.scanned_at at time zone 'Africa/Harare')::date between p_start_date and p_end_date) q;
  elsif p_report='meals' then
    select coalesce(jsonb_agg(to_jsonb(q) order by q.checked_in_at desc),'[]'::jsonb) into v_result
    from (select c.service_date,c.checked_in_at,s.registration_number,s.full_name,c.meal_session,c.check_in_source
          from public.check_ins c join public.students s on s.id=c.student_id
          where c.service_date between p_start_date and p_end_date) q;
  else
    return jsonb_build_object('status','invalid','message','Unknown report type.');
  end if;
  return jsonb_build_object('status','success','report',p_report,'rows',v_result);
end;
$$;

-- Keep the legacy dashboard route working while the new modular app is deployed.
create or replace function public.campus_dashboard(p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v jsonb;
begin
  v := public.student_services_dashboard(p_pin);
  if coalesce(v->>'status','') <> 'success' then return v; end if;
  return jsonb_build_object('status','success','counts',v->'counts','students',v->'students','recent_movements',v->'recent_movements');
end;
$$;

revoke all on function public._gate_pass_deadline(timestamptz) from public, anon, authenticated;
grant execute on function public.student_submit_gate_pass(text,text,text,timestamptz,timestamptz,text) to anon, authenticated;
grant execute on function public.student_gate_pass_status(text) to anon, authenticated;
grant execute on function public.dashboard_gate_pass_decision(text,uuid,text,text,text) to anon, authenticated;
grant execute on function public.gate_record_movement_v3(text,text,text,text) to anon, authenticated;
grant execute on function public.gate_duty_record(text,text,text,text) to anon, authenticated;
grant execute on function public.student_services_dashboard(text) to anon, authenticated;
grant execute on function public.student_services_update_setting(text,text,jsonb) to anon, authenticated;
grant execute on function public.student_services_export(text,text,date,date) to anon, authenticated;
grant execute on function public.campus_dashboard(text) to anon, authenticated;
