const MEALS=['Breakfast','Lunch','Break-fast 4pm','Supper'];
const {$,esc,normalizeReg,localDate,setOnlineBadge,downloadCsv,registerSW}=AMFCC;
let staffMeal='',studentMeal='',activePin='',refreshTimer=null,scanTarget='';
function showScreen(id){document.querySelectorAll('.screen').forEach(el=>el.classList.remove('active'));$(id).classList.add('active');clearInterval(refreshTimer);if(id==='staff'){refreshDashboard();refreshTimer=setInterval(refreshDashboard,10000);setTimeout(()=>$('staffReg').focus(),60)}if(id==='student')setTimeout(()=>$('studentReg').focus(),60)}
function renderMealButtons(containerId,type){const selected=type==='staff'?staffMeal:studentMeal;$(containerId).innerHTML=MEALS.map(meal=>`<button class="btn meal ${selected===meal?'selected':''}" data-meal="${esc(meal)}" data-type="${type}">${esc(meal)}</button>`).join('')}
function renderMeals(){renderMealButtons('staffMeals','staff');renderMealButtons('studentMeals','student')}
document.addEventListener('click',event=>{const button=event.target.closest('[data-meal]');if(!button)return;if(button.dataset.type==='staff')staffMeal=button.dataset.meal;else studentMeal=button.dataset.meal;renderMeals()});
function message(kind,title,body){$('resultBox').className='result-box '+kind;$('resultBox').innerHTML=`<div class="icon">${kind==='good'?'✓':kind==='warn'?'⚠':'✕'}</div><h2>${esc(title)}</h2>${body}`;$('result').classList.add('open');setTimeout(hideResult,2800)}
function hideResult(){$('result').classList.remove('open');const active=document.querySelector('.screen.active');if(active?.id==='staff')$('staffReg').focus();if(active?.id==='student')$('studentReg').focus()}
async function validatePin(){const pin=$('pinInput').value.trim();if(!/^\d{4}$/.test(pin))return showPinError('Enter the four-digit PIN.');$('pinContinue').disabled=true;const {data,error}=await amfccDb.rpc('staff_dashboard',{p_pin:pin,p_service_date:localDate()});$('pinContinue').disabled=false;if(error||data?.status!=='success')return showPinError('Incorrect PIN.');activePin=pin;$('pinModal').classList.remove('open');showScreen('staff')}
function showPinError(text){$('pinError').textContent=text;$('pinError').style.display='block'}
async function refreshDashboard(){if(!activePin||!navigator.onLine)return;const {data,error}=await amfccDb.rpc('staff_dashboard',{p_pin:activePin,p_service_date:localDate()});if(error||data?.status!=='success')return;const counts=data.counts||{};$('counts').innerHTML=MEALS.map(meal=>`<div class="count"><b>${counts[meal]||0}</b><span>${esc(meal)}</span></div>`).join('');$('plan').innerHTML=`To cook today: <b>Lunch ${data.lunch_to_cook||0}</b> · <b>Supper ${data.supper_to_cook||0}</b>`}
async function checkIn(type){const meal=type==='staff'?staffMeal:studentMeal,input=$(type+'Reg'),reg=normalizeReg(input.value);if(!meal)return message('bad','Choose a meal','<p>Select the meal first.</p>');if(!/^\d{5}$/.test(reg))return message('bad','Check the number','<p>Enter a five-digit registration number.</p>');if(!navigator.onLine)return message('bad','No connection','<p>Connect to the internet and try again.</p>');const fn=type==='staff'?'staff_check_in':'check_in_student_public';const args=type==='staff'?{p_pin:activePin,p_registration_number:reg,p_meal_session:meal,p_service_date:localDate()}:{p_registration_number:reg,p_meal_session:meal,p_service_date:localDate()};const {data,error}=await amfccDb.rpc(fn,args);input.value='';if(error)return message('bad','Could not save',`<p>${esc(error.message)}</p>`);const name=data?.full_name?`<div class="name">${esc(data.full_name)}</div>`:'';if(data?.status==='checked_in')message('good','CHECKED IN',`${name}<p>${esc(data.registration_number||reg)} · ${esc(data.meal_session||meal)}</p>`);else if(data?.status==='duplicate')message('warn','ALREADY CHECKED IN',`${name}<p>${esc(meal)}</p>`);else message('bad',data?.status==='not_eligible'?'NOT ELIGIBLE':'NOT SAVED',`${name}<p>${esc(data?.message||'Please try again.')}</p>`);if(type==='staff')refreshDashboard()}
async function exportRows(scope){const {data,error}=await amfccDb.rpc('staff_export',{p_pin:activePin,p_scope:scope,p_service_date:localDate()});if(error)return message('bad','Export failed',`<p>${esc(error.message)}</p>`);try{downloadCsv(data||[],`meal-checkins-${scope}-${localDate()}.csv`)}catch(err){message('warn','Nothing to export',`<p>${esc(err.message)}</p>`)}}
function startCamera(type){scanTarget=type;AMFCCScanner.start({video:$('video'),overlay:$('camera'),onResult:value=>{const reg=normalizeReg(value);if(/^\d{5}$/.test(reg)){ $(scanTarget+'Reg').value=reg; checkIn(scanTarget)}else message('bad','Card not recognised','<p>Use a student ID QR code.</p>')},onError:text=>message('bad','Camera unavailable',`<p>${esc(text)}</p>`)})}
$('staffOpen').onclick=()=>{$('pinInput').value='';$('pinError').style.display='none';$('pinModal').classList.add('open');setTimeout(()=>$('pinInput').focus(),60)};$('studentOpen').onclick=()=>showScreen('student');document.querySelectorAll('.backHome').forEach(b=>b.onclick=()=>showScreen('home'));$('pinContinue').onclick=validatePin;$('pinCancel').onclick=()=>$('pinModal').classList.remove('open');$('pinInput').onkeydown=e=>{if(e.key==='Enter')validatePin()};$('staffCheck').onclick=()=>checkIn('staff');$('studentCheck').onclick=()=>checkIn('student');$('exportToday').onclick=()=>exportRows('today');$('exportAll').onclick=()=>exportRows('all');document.querySelectorAll('[data-scan]').forEach(b=>b.onclick=()=>startCamera(b.dataset.scan));$('cameraCancel').onclick=()=>AMFCCScanner.stop();$('result').onclick=hideResult;window.addEventListener('online',()=>{setOnlineBadge('staffStatus');setOnlineBadge('studentStatus')});window.addEventListener('offline',()=>{setOnlineBadge('staffStatus');setOnlineBadge('studentStatus')});renderMeals();setOnlineBadge('staffStatus');setOnlineBadge('studentStatus');registerSW();
